import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { generateCoachAccessCode } from "@/lib/accessCodes";
import { PLAN_TEMPLATES } from "@/lib/templates";
import { getUserAccountStatusMap } from "@/lib/userDeactivation";
import { z } from "zod";
import type { Prisma } from "@prisma/client";
import { randomBytes } from "crypto";

// GET codes generated by this coach, OR all codes if Super Admin
export async function GET(req: Request) {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const user = await prisma.user.findUnique({ where: { clerkId: userId } });
    if (!user || !["COACH", "SUPER_ADMIN"].includes(user.role)) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const url = new URL(req.url);
    const filter = url.searchParams.get("filter") || "ALL";

    const where: Prisma.AccessCodeWhereInput = {};
    if (user.role !== "SUPER_ADMIN") {
        where.generatedBy = user.id;
    }

    if (filter === "USED") {
        where.usedById = { not: null };
    } else if (filter === "UNUSED") {
        where.usedById = null;
        where.isActive = true;
    } else if (filter === "INACTIVE") {
        where.isActive = false;
    }

    const codes = await prisma.accessCode.findMany({
        where,
        include: {
            plan: { select: { name: true } },
            usedBy: { select: { id: true, name: true, email: true } },
        },
        orderBy: { createdAt: "desc" },
    });
    const accountStatusMap = await getUserAccountStatusMap(codes.flatMap((c) => c.usedBy?.id ? [c.usedBy.id] : []));

    return NextResponse.json(codes.map(c => ({
        ...c,
        planName: c.plan?.name ?? null,
        usedByName: c.usedBy
            ? (accountStatusMap.get(c.usedBy.id)?.isDeleted
                ? accountStatusMap.get(c.usedBy.id)?.deletedName ?? c.usedBy.name
                : c.usedBy.name)
            : null,
        usedByEmail: c.usedBy
            ? (accountStatusMap.get(c.usedBy.id)?.isDeleted
                ? accountStatusMap.get(c.usedBy.id)?.deletedEmail ?? c.usedBy.email
                : c.usedBy.email)
            : null,
        usedById: c.usedBy?.id ?? null,
        usedByStatus: c.usedBy
            ? (accountStatusMap.get(c.usedBy.id)?.isDeleted
                ? "DELETED"
                : accountStatusMap.get(c.usedBy.id)?.isDeactivated
                    ? "DEACTIVATED"
                    : "ACTIVE")
            : null,
        upgradesTo: c.upgradesTo,
    })));
}

// DELETE a code (Super Admin only)
export async function DELETE(req: Request) {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const user = await prisma.user.findUnique({ where: { clerkId: userId } });
    if (!user) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

    const { id } = await req.json();
    if (!id) return NextResponse.json({ error: "ID required" }, { status: 400 });

    const code = await prisma.accessCode.findUnique({ where: { id } });
    if (!code) return NextResponse.json({ error: "Not found" }, { status: 404 });

    // Only allow Super Admins or the coach who generated it to delete
    if (user.role !== "SUPER_ADMIN" && code.generatedBy !== user.id) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    await prisma.accessCode.delete({ where: { id } });
    return NextResponse.json({ success: true });
}

const codeSchema = z.object({
    planId: z.string().nullable().optional(),
    templateId: z.string().nullable().optional(),
    upgradesTo: z.enum(["PREMIUM", "COACH"]).default("PREMIUM"),
    expiresInHours: z.number().int().positive().optional(),
});

async function getOrCreateTemplatePlan(templateId: string, creatorId: string) {
    const template = PLAN_TEMPLATES[templateId];
    if (!template) return null;

    const existing = await prisma.plan.findFirst({
        where: { creatorId, type: "PREBUILT" as never, name: template.name },
        select: { id: true },
    });
    if (existing) return existing.id;

    const plan = await prisma.plan.create({
        data: {
            name: template.name,
            description: template.description,
            type: "PREBUILT" as never,
            creatorId,
            shareCode: randomBytes(4).toString("hex").toUpperCase(),
            weeks: {
                create: [{
                    weekNumber: 1,
                    workouts: {
                        create: template.workouts.map((workout) => ({
                            name: workout.name,
                            dayNumber: workout.dayNumber,
                            dayOfWeek: (workout.dayNumber - 1) % 7,
                            exercises: {
                                create: workout.exercises.map((exercise, index) => ({
                                    name: exercise.name,
                                    sets: exercise.sets,
                                    reps: exercise.reps,
                                    order: index,
                                })),
                            },
                        })),
                    },
                }],
            },
        },
        select: { id: true },
    });

    return plan.id;
}

// POST generate a new access code
export async function POST(req: Request) {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const user = await prisma.user.findUnique({ where: { clerkId: userId } });
    if (!user || !["COACH", "SUPER_ADMIN"].includes(user.role)) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await req.json();
    const parsed = codeSchema.safeParse(body);
    if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });

    const upgradesTo = parsed.data.upgradesTo as "PREMIUM" | "COACH";

    if (upgradesTo === "COACH" && user.role !== "SUPER_ADMIN") {
        return NextResponse.json({ error: "Only admins can generate coach codes" }, { status: 403 });
    }

    let expiresAt: Date | null = null;
    if (parsed.data.expiresInHours) {
        expiresAt = new Date();
        expiresAt.setHours(expiresAt.getHours() + parsed.data.expiresInHours);
    }

    const planId = upgradesTo === "COACH"
        ? null
        : parsed.data.planId ?? (parsed.data.templateId ? await getOrCreateTemplatePlan(parsed.data.templateId, user.id) : null);

    const code = await prisma.accessCode.create({
        data: {
            code: await generateCoachAccessCode(prisma, user),
            planId,
            generatedBy: user.id,
            upgradesTo,
            expiresAt,
        },
    });

    return NextResponse.json(code, { status: 201 });
}
