import type { SpecialDefinition } from "./types";

export const SPECIAL_ACHIEVEMENTS: SpecialDefinition[] = [
    {
        key: "first-step",
        name: "First Step",
        description: "Complete your first workout.",
        icon: "trophy",
        category: "special",
        rarity: "common",
    },
    {
        key: "first-checkin",
        name: "First Check-in",
        description: "Submit your first weekly check-in.",
        icon: "clipboard",
        category: "checkins",
        rarity: "common",
    },
    {
        key: "first-pr",
        name: "First PR",
        description: "Set your first personal record.",
        icon: "zap",
        category: "prs",
        rarity: "common",
    },
    {
        key: "first-weight-pr",
        name: "First Weight PR",
        description: "Hit your first weight personal record.",
        icon: "trending",
        category: "prs",
        rarity: "common",
    },
    {
        key: "first-rep-pr",
        name: "First Rep PR",
        description: "Hit your first rep personal record.",
        icon: "zap",
        category: "prs",
        rarity: "common",
    },
    {
        key: "first-estimated-1rm",
        name: "First Estimated 1RM",
        description: "Log a weighted strength set that yields an estimated 1RM.",
        icon: "trending",
        category: "prs",
        rarity: "common",
    },
    {
        key: "onboarding-complete",
        name: "Onboarding Complete",
        description: "Finish your athlete setup.",
        icon: "star",
        category: "meta",
        rarity: "common",
    },
    {
        key: "first-plan",
        name: "First Plan",
        description: "Build your first workout plan.",
        icon: "folder",
        category: "plans",
        rarity: "common",
    },
    {
        key: "shared-plan",
        name: "Shared Plan",
        description: "Make a workout plan public on your profile.",
        icon: "share",
        category: "plans",
        rarity: "uncommon",
    },
    {
        key: "worth-copying",
        name: "Worth Copying",
        description: "Have another athlete copy one of your public plans.",
        icon: "copy",
        category: "plans",
        rarity: "rare",
    },
    {
        key: "perfect-month",
        name: "Perfect Month",
        description: "Complete every scheduled workout across a full calendar month.",
        icon: "calendar",
        category: "consistency",
        rarity: "rare",
    },
    {
        key: "flawless-100",
        name: "Flawless 100",
        description: "Keep a 100-day adherence streak without missing a session.",
        icon: "flame",
        category: "consistency",
        rarity: "epic",
    },
    {
        key: "one-year-strong",
        name: "One Year Strong",
        description: "Stay active on TOLG for a full year with training logged.",
        icon: "award",
        category: "meta",
        rarity: "epic",
    },
    {
        key: "secret-comeback",
        name: "Comeback",
        description: "Complete a workout after 14 or more days away.",
        icon: "flame",
        category: "special",
        rarity: "rare",
        secret: true,
    },
    {
        key: "secret-volume-day",
        name: "Volume Day",
        description: "Complete 20 or more sets in a single session.",
        icon: "layers",
        category: "special",
        rarity: "rare",
        secret: true,
    },
    {
        key: "secret-early-bird",
        name: "Early Bird",
        description: "Complete a workout before 7am local time.",
        icon: "clock",
        category: "special",
        rarity: "uncommon",
        secret: true,
    },
];

const byKey = new Map(SPECIAL_ACHIEVEMENTS.map((d) => [d.key, d]));

export function getSpecialByKey(key: string): SpecialDefinition | undefined {
    return byKey.get(key);
}
