/**
 * Canonical Back exercise catalog.
 *
 * Same architecture as Chest:
 * - `name` is the only GlobalExercise row we seed
 * - `aliases` are search + identity synonyms; never separate DB rows
 * - Migration remaps history via mergeExercisesIntoTarget
 */

/** @typedef {{
 *   name: string,
 *   muscleGroup: "Back" | "Hamstrings",
 *   equipment: string,
 *   movementType: string,
 *   primaryMuscles: string[],
 *   secondaryMuscles: string[],
 *   aliases?: string[],
 *   instructions?: string,
 * }} BackCatalogEntry */

/** @type {BackCatalogEntry[]} */
const BACK_CATALOG = [
    // ── Pull-Ups / Chin-Ups ──────────────────────────────────────────────────
    {
        name: "Pull-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps", "forearms"],
        aliases: ["Pull Up", "Pullup", "Pull-Ups", "Pull Ups"],
        instructions: "Hang from a bar with an overhand grip, pull until your chin clears the bar, then lower with control.",
    },
    {
        name: "Chin-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats", "biceps"],
        secondaryMuscles: ["upperBack", "forearms"],
        aliases: ["Chin Up", "Chinup", "Chin-Ups"],
        instructions: "Hang with an underhand grip and pull until your chin clears the bar.",
    },
    {
        name: "Neutral Grip Pull-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Neutral-Grip Pull-Up", "Neutral Grip Pullup", "Hammer Grip Pull-Up"],
        instructions: "Use parallel handles and pull until the chin clears the hands.",
    },
    {
        name: "Close Grip Pull-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upperBack"],
        aliases: ["Close-Grip Pull-Up", "Close Grip Pullup"],
    },
    {
        name: "Wide Grip Pull-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Wide-Grip Pull-Up", "Wide Grip Pullup"],
    },
    {
        name: "Weighted Pull-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Weighted Pullup", "Weighted Pull-Ups"],
        instructions: "Perform a pull-up with added load via a belt, vest, or dumbbell.",
    },
    {
        name: "Weighted Chin-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats", "biceps"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Weighted Chinup", "Weighted Chin-Ups"],
    },
    {
        name: "Assisted Pull-Up",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Machine Assisted Pull-Up", "Assisted Pullup"],
        instructions: "Use an assisted pull-up machine; select enough assistance to complete full reps with control.",
    },
    {
        name: "Assisted Chin-Up",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats", "biceps"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Machine Assisted Chin-Up"],
    },
    {
        name: "Band Assisted Pull-Up",
        muscleGroup: "Back",
        equipment: "Resistance Band",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Banded Pull-Up", "Resistance Band Assisted Pull-Up"],
        instructions: "Loop a band over the bar and under a knee or foot to assist the pull-up.",
    },
    {
        name: "Ring Pull-Up",
        muscleGroup: "Back",
        equipment: "Rings",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps", "forearms"],
        aliases: ["Gymnastic Ring Pull-Up"],
    },
    {
        name: "Sternum Pull-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Sternum Pullup", "Gironda Pull-Up"],
        instructions: "Lean back as you pull so the sternum approaches the bar, emphasizing upper-back involvement.",
    },

    // ── Lat Pulldowns ────────────────────────────────────────────────────────
    {
        name: "Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Lat Pull Down", "Cable Lat Pulldown", "Front Lat Pulldown"],
        instructions: "Sit tall, pull the bar to the upper chest, then control the return overhead.",
    },
    {
        name: "Wide Grip Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Wide-Grip Lat Pulldown"],
    },
    {
        name: "Close Grip Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upperBack"],
        aliases: ["Close-Grip Lat Pulldown"],
    },
    {
        name: "Neutral Grip Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upperBack"],
        aliases: ["Neutral-Grip Lat Pulldown", "Hammer Grip Lat Pulldown"],
    },
    {
        name: "Reverse Grip Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats", "biceps"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Reverse-Grip Lat Pulldown", "Underhand Lat Pulldown"],
    },
    {
        name: "Single Arm Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Single-Arm Lat Pulldown", "One Arm Lat Pulldown"],
    },
    {
        name: "Kneeling Single Arm Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps", "core"],
        aliases: ["Kneeling Single-Arm Lat Pulldown"],
    },
    {
        name: "Half Kneeling Single Arm Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps", "core"],
        aliases: ["Half-Kneeling Single Arm Lat Pulldown"],
    },
    {
        name: "Machine Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Lat Pulldown Machine"],
    },
    {
        name: "Plate Loaded Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Plate Loaded Machine",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Plate-Loaded Lat Pulldown"],
    },
    {
        name: "Assisted Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: [],
    },

    // ── Straight arm / pullover ──────────────────────────────────────────────
    {
        name: "Straight Arm Cable Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["triceps", "core"],
        aliases: ["Straight-Arm Pulldown", "Straight Arm Pulldown", "Straight Arm Lat Pulldown"],
        instructions: "Keep arms nearly straight and pull the bar or handle from overhead down toward the thighs, isolating the lats.",
    },
    {
        name: "Rope Straight Arm Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["triceps", "core"],
        aliases: ["Straight Arm Rope Pulldown"],
    },
    {
        name: "Single Arm Straight Arm Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["core"],
        aliases: ["Single-Arm Straight Arm Pulldown"],
    },
    {
        name: "Cable Lat Pullover",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["chest", "triceps"],
        aliases: ["Lat Pullover", "Cable Pullover"],
        instructions: "From a high cable, pull the attachment in an arc toward the hips while keeping a soft elbow bend.",
    },
    {
        name: "Single Arm Cable Lat Pullover",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["core"],
        aliases: ["Single-Arm Cable Lat Pullover"],
    },
    {
        name: "Dumbbell Pullover",
        muscleGroup: "Back",
        equipment: "Dumbbell",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["chest", "triceps"],
        aliases: ["DB Pullover", "Dumbbell Lat Pullover"],
        instructions: "Lie on a bench holding a dumbbell above the chest, lower it behind the head in an arc, then pull back over the chest.",
    },
    {
        name: "Machine Pullover",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["chest"],
        aliases: ["Nautilus Pullover"],
        instructions: "Sit in the pullover machine, drive the pads through an arc from overhead toward the hips using the lats.",
    },
    {
        name: "Resistance Band Straight Arm Pulldown",
        muscleGroup: "Back",
        equipment: "Resistance Band",
        movementType: "Isolation",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["core"],
        aliases: ["Band Straight Arm Pulldown"],
    },

    // ── Barbell rows ─────────────────────────────────────────────────────────
    {
        name: "Barbell Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "shoulders", "lowerBack"],
        aliases: ["Bent Over Row", "Bent-Over Row", "Barbell Bent Over Row", "BB Row"],
        instructions: "Hinge at the hips, pull the bar to the lower torso, then lower under control.",
    },
    {
        name: "Pendlay Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "lowerBack"],
        aliases: [],
        instructions: "From a dead stop on the floor each rep, explosively row the bar to the torso, then return to the floor.",
    },
    {
        name: "Yates Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: [],
        instructions: "Use an underhand grip with a more upright torso and row the bar toward the waist.",
    },
    {
        name: "Underhand Barbell Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Reverse Grip Barbell Row", "Underhand Bent Over Row"],
    },
    {
        name: "Wide Grip Barbell Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack"],
        secondaryMuscles: ["lats", "biceps"],
        aliases: ["Wide-Grip Barbell Row"],
    },
    {
        name: "Seal Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Barbell Seal Row", "Prone Bench Row"],
        instructions: "Lie face-down on an elevated bench and row the bar without using leg drive.",
    },
    {
        name: "Barbell Chest Supported Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Chest-Supported Row", "Chest Supported Row", "Chest Supported Barbell Row"],
        instructions: "Brace your chest on an incline bench and row the bar without swinging the torso.",
    },

    // ── Dumbbell rows ────────────────────────────────────────────────────────
    {
        name: "Single Arm Dumbbell Row",
        muscleGroup: "Back",
        equipment: "Dumbbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps", "core"],
        aliases: [
            "Single-Arm Dumbbell Row",
            "One Arm Dumbbell Row",
            "One-Arm Dumbbell Row",
            "Dumbbell Row",
            "DB Row",
            "Single Arm DB Row",
        ],
        instructions: "Brace on a bench, pull the dumbbell to the hip with the elbow close to the torso, then lower fully.",
    },
    {
        name: "Dumbbell Bent Over Row",
        muscleGroup: "Back",
        equipment: "Dumbbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "lowerBack"],
        aliases: ["Two Arm Dumbbell Row", "Bent Over Dumbbell Row"],
        instructions: "Hinge forward holding two dumbbells and row both to the hips together.",
    },
    {
        name: "Chest Supported Dumbbell Row",
        muscleGroup: "Back",
        equipment: "Dumbbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Chest-Supported Dumbbell Row", "Incline Dumbbell Row"],
    },
    {
        name: "Incline Bench Dumbbell Row",
        muscleGroup: "Back",
        equipment: "Dumbbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Incline Bench DB Row"],
    },
    {
        name: "Dumbbell Seal Row",
        muscleGroup: "Back",
        equipment: "Dumbbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["DB Seal Row"],
    },
    {
        name: "Renegade Row",
        muscleGroup: "Back",
        equipment: "Dumbbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["core", "shoulders", "triceps"],
        aliases: [],
        instructions: "From a plank on dumbbells, row one dumbbell while bracing hard to keep the hips square.",
    },

    // ── Cable rows ───────────────────────────────────────────────────────────
    {
        name: "Seated Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Cable Row", "Seated Row"],
        instructions: "Sit tall, pull the handle to the torso, squeeze the shoulder blades, then extend the arms under control.",
    },
    {
        name: "Close Grip Seated Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Close-Grip Cable Row", "Close Grip Cable Row", "Close-Grip Seated Cable Row"],
        instructions: "Use a close/V-handle and row to the midsection while keeping the torso stable.",
    },
    {
        name: "Wide Grip Seated Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack"],
        secondaryMuscles: ["lats", "biceps"],
        aliases: ["Wide-Grip Cable Row", "Wide Grip Cable Row", "Wide-Grip Seated Cable Row"],
        instructions: "Use a wide bar attachment and row toward the upper torso.",
    },
    {
        name: "Neutral Grip Seated Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Neutral-Grip Seated Cable Row"],
    },
    {
        name: "Underhand Seated Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Reverse Grip Seated Cable Row", "Underhand Cable Row"],
    },
    {
        name: "Single Arm Seated Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Single-Arm Seated Cable Row"],
    },
    {
        name: "Single Arm Standing Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Single-Arm Standing Cable Row", "Standing Single Arm Cable Row"],
    },
    {
        name: "Single Arm Kneeling Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Single-Arm Kneeling Cable Row"],
    },
    {
        name: "Rope Seated Cable Row",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Seated Rope Cable Row"],
    },

    // ── Machine / plate loaded rows ──────────────────────────────────────────
    {
        name: "Machine Row",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Seated Machine Row", "Selectorized Row"],
    },
    {
        name: "Chest Supported Machine Row",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Chest-Supported Machine Row"],
    },
    {
        name: "Plate Loaded Row",
        muscleGroup: "Back",
        equipment: "Plate Loaded Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Plate-Loaded Row", "Hammer Strength Row", "HS Row"],
    },
    {
        name: "Plate Loaded Chest Supported Row",
        muscleGroup: "Back",
        equipment: "Plate Loaded Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Plate-Loaded Chest Supported Row", "Hammer Strength Chest Supported Row"],
    },
    {
        name: "Single Arm Machine Row",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Single-Arm Machine Row"],
    },
    {
        name: "Single Arm Plate Loaded Row",
        muscleGroup: "Back",
        equipment: "Plate Loaded Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Single-Arm Plate Loaded Row", "Hammer Strength Single Arm Row"],
    },
    {
        name: "High Row Machine",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack"],
        secondaryMuscles: ["lats", "biceps"],
        aliases: ["Machine High Row"],
    },
    {
        name: "Single Arm High Row Machine",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack"],
        secondaryMuscles: ["lats", "biceps"],
        aliases: ["Single-Arm High Row Machine"],
    },
    {
        name: "Low Row Machine",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Machine Low Row"],
    },
    {
        name: "Single Arm Low Row Machine",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps"],
        aliases: ["Single-Arm Low Row Machine"],
    },
    {
        name: "Iso-Lateral Row",
        muscleGroup: "Back",
        equipment: "Plate Loaded Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Isolateral Row", "Iso Lateral Row"],
    },

    // ── T-Bar / landmine ─────────────────────────────────────────────────────
    {
        name: "T-Bar Row",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "lowerBack"],
        aliases: ["T Bar Row", "TBar Row"],
        instructions: "Straddle the bar, hinge forward, and row the sleeve or handle to the torso.",
    },
    {
        name: "Chest Supported T-Bar Row",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Chest-Supported T-Bar Row", "Supported T-Bar Row"],
    },
    {
        name: "Landmine Row",
        muscleGroup: "Back",
        equipment: "Landmine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Landmine Barbell Row"],
    },
    {
        name: "Meadows Row",
        muscleGroup: "Back",
        equipment: "Landmine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "core"],
        aliases: [],
        instructions: "Stand perpendicular to a landmine bar, hinge, and row the end of the bar with a staggered stance.",
    },
    {
        name: "Single Arm Landmine Row",
        muscleGroup: "Back",
        equipment: "Landmine",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Single-Arm Landmine Row"],
    },

    // ── Bodyweight rows ──────────────────────────────────────────────────────
    {
        name: "Inverted Row",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Australian Pull-Up", "Australian Pullup", "Bodyweight Row", "Horizontal Pull-Up"],
        instructions: "Hang under a bar with a straight body and pull the chest to the bar.",
    },
    {
        name: "Ring Row",
        muscleGroup: "Back",
        equipment: "Rings",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Gymnastic Ring Row"],
    },
    {
        name: "Feet Elevated Inverted Row",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Feet Elevated Bodyweight Row"],
    },
    {
        name: "Weighted Inverted Row",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps", "core"],
        aliases: [],
    },

    // ── Deadlifts (tracked under Back; RDL stays Hamstrings-only below) ──────
    {
        name: "Conventional Deadlift",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["lowerBack", "glutes", "hamstrings"],
        secondaryMuscles: ["traps", "lats", "forearms", "quads", "core"],
        aliases: ["Deadlift", "Barbell Deadlift", "Conventional Barbell Deadlift", "BB Deadlift"],
        instructions: "Stand with the bar over mid-foot, brace, push the floor away, and lock out the hips and knees together.",
    },
    {
        name: "Sumo Deadlift",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["glutes", "hamstrings", "quads"],
        secondaryMuscles: ["lowerBack", "traps", "core"],
        aliases: ["Sumo Barbell Deadlift"],
        instructions: "Take a wide stance with toes out, grip inside the knees, and stand the bar up while keeping the torso more upright.",
    },
    {
        name: "Trap Bar Deadlift",
        muscleGroup: "Back",
        equipment: "Trap Bar",
        movementType: "Hip Hinge",
        primaryMuscles: ["glutes", "quads", "hamstrings"],
        secondaryMuscles: ["lowerBack", "traps", "core"],
        aliases: ["Hex Bar Deadlift", "Trapbar Deadlift"],
        instructions: "Stand inside the trap bar, grip the handles, brace, and stand tall by driving through the floor.",
    },
    {
        name: "Deficit Deadlift",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["hamstrings", "glutes", "lowerBack"],
        secondaryMuscles: ["traps", "quads", "core"],
        aliases: [],
        instructions: "Stand on a low plate or platform and deadlift from the increased range of motion.",
    },
    {
        name: "Rack Pull",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["upperBack", "traps", "lowerBack"],
        secondaryMuscles: ["glutes", "hamstrings", "forearms"],
        aliases: ["Partial Deadlift", "Above Knee Rack Pull"],
        instructions: "Set the bar on pins around knee height and lock out the deadlift from that position.",
    },
    {
        name: "Block Pull",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["upperBack", "traps", "lowerBack"],
        secondaryMuscles: ["glutes", "hamstrings"],
        aliases: ["Block Deadlift", "Elevated Deadlift"],
        instructions: "Rest the plates on blocks and pull from the elevated starting height.",
    },
    {
        name: "Snatch Grip Deadlift",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["upperBack", "hamstrings", "glutes"],
        secondaryMuscles: ["lowerBack", "traps", "forearms"],
        aliases: ["Snatch-Grip Deadlift"],
    },
    {
        name: "Paused Deadlift",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["hamstrings", "glutes", "lowerBack"],
        secondaryMuscles: ["traps", "core"],
        aliases: ["Pause Deadlift"],
        instructions: "Deadlift with a deliberate pause just below or at the knees before finishing the lockout.",
    },
    // RDL remains Hamstrings category — single record, searchable via aliases
    {
        name: "Romanian Deadlift",
        muscleGroup: "Hamstrings",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["hamstrings", "glutes"],
        secondaryMuscles: ["lowerBack", "core"],
        aliases: ["RDL", "Barbell Romanian Deadlift", "Barbell RDL"],
        instructions: "From standing, push the hips back with a soft knee bend, lower the bar along the thighs, then drive the hips forward to stand.",
    },

    // ── Lower back / erectors ────────────────────────────────────────────────
    {
        name: "Back Extension",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Isolation",
        primaryMuscles: ["lowerBack"],
        secondaryMuscles: ["glutes", "hamstrings"],
        aliases: ["Hyperextension", "Hyper Extension", "Back Extensions"],
        instructions: "On a back-extension bench, hinge at the hips and raise the torso until it aligns with the legs.",
    },
    {
        name: "45 Degree Back Extension",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Isolation",
        primaryMuscles: ["lowerBack"],
        secondaryMuscles: ["glutes", "hamstrings"],
        aliases: ["45-Degree Back Extension", "45 Degree Hyperextension"],
        instructions: "Use a 45-degree hyperextension bench; hinge and extend until the body forms a straight line.",
    },
    {
        name: "90 Degree Back Extension",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Isolation",
        primaryMuscles: ["lowerBack"],
        secondaryMuscles: ["glutes", "hamstrings"],
        aliases: ["90-Degree Back Extension", "Horizontal Back Extension", "GHD Back Extension"],
        instructions: "On a horizontal or GHD setup, hinge and extend the torso parallel to the floor.",
    },
    {
        name: "Weighted Back Extension",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Isolation",
        primaryMuscles: ["lowerBack"],
        secondaryMuscles: ["glutes", "hamstrings"],
        aliases: ["Weighted Hyperextension"],
    },
    {
        name: "Machine Back Extension",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Isolation",
        primaryMuscles: ["lowerBack"],
        secondaryMuscles: ["glutes"],
        aliases: ["Back Extension Machine"],
    },
    {
        name: "Reverse Hyperextension",
        muscleGroup: "Back",
        equipment: "Machine",
        movementType: "Isolation",
        primaryMuscles: ["glutes", "hamstrings", "lowerBack"],
        secondaryMuscles: ["core"],
        aliases: ["Reverse Hyper", "Reverse Hyperextensions"],
        instructions: "Lie prone on the reverse hyper and swing the legs up by contracting the glutes and hamstrings.",
    },
    {
        name: "Good Morning",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["hamstrings", "lowerBack"],
        secondaryMuscles: ["glutes", "core"],
        aliases: ["Good Mornings"],
        instructions: "Bar on the upper back, soft knees, hinge the hips back until you feel a hamstring stretch, then stand tall.",
    },
    {
        name: "Barbell Good Morning",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["hamstrings", "lowerBack"],
        secondaryMuscles: ["glutes", "core"],
        aliases: [],
    },
    {
        name: "Seated Good Morning",
        muscleGroup: "Back",
        equipment: "Barbell",
        movementType: "Hip Hinge",
        primaryMuscles: ["lowerBack", "hamstrings"],
        secondaryMuscles: ["glutes"],
        aliases: [],
    },
    {
        name: "Superman",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Isolation",
        primaryMuscles: ["lowerBack"],
        secondaryMuscles: ["glutes"],
        aliases: ["Superman Hold"],
        instructions: "Lie face-down and lift the arms and legs off the floor, squeezing the lower back and glutes.",
    },
    {
        name: "Bird Dog",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Isolation",
        primaryMuscles: ["core", "lowerBack"],
        secondaryMuscles: ["glutes"],
        aliases: ["Bird-Dog"],
        instructions: "From all fours, extend opposite arm and leg while keeping the hips level, then switch sides.",
    },

    // ── Other ────────────────────────────────────────────────────────────────
    {
        name: "Scapular Pull-Up",
        muscleGroup: "Back",
        equipment: "Bodyweight",
        movementType: "Isolation",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["traps"],
        aliases: ["Scap Pull-Up", "Scapular Pullup"],
        instructions: "Hang from the bar and depress/retract the scapulae without bending the elbows.",
    },
    {
        name: "Cable Scapular Pulldown",
        muscleGroup: "Back",
        equipment: "Cable",
        movementType: "Isolation",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["traps"],
        aliases: ["Scapular Pulldown"],
    },
    {
        name: "Resistance Band Lat Pulldown",
        muscleGroup: "Back",
        equipment: "Resistance Band",
        movementType: "Vertical Pull",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upperBack", "biceps"],
        aliases: ["Band Lat Pulldown"],
    },
    {
        name: "Resistance Band Row",
        muscleGroup: "Back",
        equipment: "Resistance Band",
        movementType: "Horizontal Pull",
        primaryMuscles: ["upperBack", "lats"],
        secondaryMuscles: ["biceps"],
        aliases: ["Band Row"],
    },
    {
        name: "Single Arm Resistance Band Row",
        muscleGroup: "Back",
        equipment: "Resistance Band",
        movementType: "Horizontal Pull",
        primaryMuscles: ["lats", "upperBack"],
        secondaryMuscles: ["biceps", "core"],
        aliases: ["Single-Arm Band Row", "Single Arm Band Row"],
    },
];

/**
 * Identity-key aliases (must match exerciseIdentityKey normalisation).
 */
const BACK_KEY_ALIASES = {
    // Pull-ups
    "pull ups": "pull up",
    "pullups": "pull up",
    "chin ups": "chin up",
    "chinups": "chin up",
    "neutral grip pullup": "neutral grip pull up",
    "hammer grip pull up": "neutral grip pull up",
    "close grip pullup": "close grip pull up",
    "wide grip pullup": "wide grip pull up",
    "weighted pullup": "weighted pull up",
    "weighted chinup": "weighted chin up",
    "machine assisted pull up": "assisted pull up",
    "assisted pullup": "assisted pull up",
    "banded pull up": "band assisted pull up",
    "resistance band assisted pull up": "band assisted pull up",
    "gymnastic ring pull up": "ring pull up",
    "sternum pullup": "sternum pull up",
    "gironda pull up": "sternum pull up",

    // Pulldowns
    "lat pull down": "lat pulldown",
    "cable lat pulldown": "lat pulldown",
    "front lat pulldown": "lat pulldown",
    "wide grip lat pulldown": "wide grip lat pulldown",
    "close grip lat pulldown": "close grip lat pulldown",
    "neutral grip lat pulldown": "neutral grip lat pulldown",
    "hammer grip lat pulldown": "neutral grip lat pulldown",
    "reverse grip lat pulldown": "reverse grip lat pulldown",
    "underhand lat pulldown": "reverse grip lat pulldown",
    "one arm lat pulldown": "single arm lat pulldown",
    "lat pulldown machine": "machine lat pulldown",
    "plate loaded lat pulldown": "plate loaded lat pulldown",

    // Straight arm / pullover
    "straight arm pulldown": "straight arm cable pulldown",
    "straight arm lat pulldown": "straight arm cable pulldown",
    "straight arm rope pulldown": "rope straight arm pulldown",
    "lat pullover": "cable lat pullover",
    "cable pullover": "cable lat pullover",
    "db pullover": "dumbbell pullover",
    "dumbbell lat pullover": "dumbbell pullover",
    "nautilus pullover": "machine pullover",
    "band straight arm pulldown": "resistance band straight arm pulldown",

    // Barbell rows
    "bent over row": "barbell row",
    "bent over barbell row": "barbell row",
    "barbell bent over row": "barbell row",
    "bb row": "barbell row",
    "reverse grip barbell row": "underhand barbell row",
    "underhand bent over row": "underhand barbell row",
    "wide grip barbell row": "wide grip barbell row",
    "barbell seal row": "seal row",
    "prone bench row": "seal row",
    "chest supported row": "barbell chest supported row",
    "chest supported barbell row": "barbell chest supported row",

    // Dumbbell rows
    "single arm dumbbell row": "single arm dumbbell row",
    "one arm dumbbell row": "single arm dumbbell row",
    "dumbbell row": "single arm dumbbell row",
    "db row": "single arm dumbbell row",
    "single arm db row": "single arm dumbbell row",
    "two arm dumbbell row": "dumbbell bent over row",
    "bent over dumbbell row": "dumbbell bent over row",
    "chest supported dumbbell row": "chest supported dumbbell row",
    "incline dumbbell row": "chest supported dumbbell row",
    "incline bench db row": "incline bench dumbbell row",
    "db seal row": "dumbbell seal row",

    // Cable rows
    "cable row": "seated cable row",
    "seated row": "seated cable row",
    "close grip cable row": "close grip seated cable row",
    "close grip seated cable row": "close grip seated cable row",
    "wide grip cable row": "wide grip seated cable row",
    "wide grip seated cable row": "wide grip seated cable row",
    "reverse grip seated cable row": "underhand seated cable row",
    "underhand cable row": "underhand seated cable row",
    "standing single arm cable row": "single arm standing cable row",
    "seated rope cable row": "rope seated cable row",

    // Machines
    "seated machine row": "machine row",
    "selectorized row": "machine row",
    "plate loaded row": "plate loaded row",
    "hammer strength row": "plate loaded row",
    "hs row": "plate loaded row",
    "plate loaded chest supported row": "plate loaded chest supported row",
    "hammer strength chest supported row": "plate loaded chest supported row",
    "hammer strength single arm row": "single arm plate loaded row",
    "machine high row": "high row machine",
    "machine low row": "low row machine",
    "isolateral row": "iso lateral row",
    "iso lateral row": "iso lateral row",

    // T-bar / landmine
    "t bar row": "t bar row",
    "tbar row": "t bar row",
    "chest supported t bar row": "chest supported t bar row",
    "supported t bar row": "chest supported t bar row",
    "landmine barbell row": "landmine row",

    // Bodyweight rows
    "australian pull up": "inverted row",
    "australian pullup": "inverted row",
    "bodyweight row": "inverted row",
    "horizontal pull up": "inverted row",
    "gymnastic ring row": "ring row",
    "feet elevated bodyweight row": "feet elevated inverted row",

    // Deadlifts
    "deadlift": "conventional deadlift",
    "barbell deadlift": "conventional deadlift",
    "conventional barbell deadlift": "conventional deadlift",
    "bb deadlift": "conventional deadlift",
    "sumo barbell deadlift": "sumo deadlift",
    "hex bar deadlift": "trap bar deadlift",
    "trapbar deadlift": "trap bar deadlift",
    "partial deadlift": "rack pull",
    "above knee rack pull": "rack pull",
    "block deadlift": "block pull",
    "elevated deadlift": "block pull",
    "snatch grip deadlift": "snatch grip deadlift",
    "pause deadlift": "paused deadlift",
    "rdl": "romanian deadlift",
    "barbell romanian deadlift": "romanian deadlift",
    "barbell rdl": "romanian deadlift",

    // Lower back
    "hyperextension": "back extension",
    "hyper extension": "back extension",
    "back extensions": "back extension",
    "45 degree hyperextension": "45 degree back extension",
    "45 degree back extension": "45 degree back extension",
    "90 degree back extension": "90 degree back extension",
    "horizontal back extension": "90 degree back extension",
    "ghd back extension": "90 degree back extension",
    "weighted hyperextension": "weighted back extension",
    "back extension machine": "machine back extension",
    "reverse hyper": "reverse hyperextension",
    "reverse hyperextensions": "reverse hyperextension",
    "good mornings": "good morning",
    "superman hold": "superman",
    "bird dog": "bird dog",

    // Other
    "scap pull up": "scapular pull up",
    "scapular pullup": "scapular pull up",
    "scapular pulldown": "cable scapular pulldown",
    "band lat pulldown": "resistance band lat pulldown",
    "band row": "resistance band row",
    "single arm band row": "single arm resistance band row",
};

function backDictionaryEntries() {
    return BACK_CATALOG.map((entry) => ({
        name: entry.name,
        muscleGroup: entry.muscleGroup,
        ...(entry.instructions ? { instructions: entry.instructions } : {}),
    }));
}

function backSearchAliasRows() {
    const rows = [];
    for (const entry of BACK_CATALOG) {
        for (const alias of entry.aliases ?? []) {
            rows.push({
                alias,
                name: entry.name,
                muscleGroup: entry.muscleGroup,
            });
        }
    }
    return rows;
}

function backMergeTargets() {
    return BACK_CATALOG.map((entry) => ({
        targetName: entry.name,
        targetMuscleGroup: entry.muscleGroup,
        sourceNames: [...new Set([...(entry.aliases ?? [])])],
    })).filter((row) => row.sourceNames.length > 0);
}

module.exports = {
    BACK_CATALOG,
    BACK_KEY_ALIASES,
    backDictionaryEntries,
    backSearchAliasRows,
    backMergeTargets,
};
