/**
 * Canonical Biceps exercise catalog.
 *
 * Same architecture as Chest/Back/Shoulders:
 * - `name` is the only GlobalExercise row we seed
 * - `aliases` are search + identity synonyms; never separate DB rows
 * - Migration remaps history via mergeExercisesIntoTarget
 */

/** @typedef {{
 *   name: string,
 *   muscleGroup: "Biceps",
 *   equipment: string,
 *   movementType: string,
 *   primaryMuscles: string[],
 *   secondaryMuscles: string[],
 *   aliases?: string[],
 *   instructions?: string,
 * }} BicepsCatalogEntry */

/** @type {BicepsCatalogEntry[]} */
const BICEPS_CATALOG = [
    // ── Barbell / EZ Bar ─────────────────────────────────────────────────────
    {
        name: "Barbell Curl",
        muscleGroup: "Biceps",
        equipment: "Barbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Barbell Bicep Curl", "BB Curl", "Standing Barbell Curl"],
        instructions: "Stand holding a barbell with an underhand grip, curl to the shoulders without swinging, then lower under control.",
    },
    {
        name: "EZ Bar Curl",
        muscleGroup: "Biceps",
        equipment: "EZ Bar",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["EZ-Bar Curl", "EZ Curl", "Easy Bar Curl"],
        instructions: "Curl an EZ bar with an underhand grip, keeping the elbows close to the torso.",
    },
    {
        name: "Wide Grip Barbell Curl",
        muscleGroup: "Biceps",
        equipment: "Barbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Wide-Grip Barbell Curl", "Wide Grip Curl"],
    },
    {
        name: "Close Grip Barbell Curl",
        muscleGroup: "Biceps",
        equipment: "Barbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Close-Grip Barbell Curl", "Close Grip Curl"],
    },
    {
        name: "Reverse Barbell Curl",
        muscleGroup: "Biceps",
        equipment: "Barbell",
        movementType: "Curl",
        primaryMuscles: ["brachialis", "forearms"],
        secondaryMuscles: ["biceps"],
        aliases: ["Reverse Grip Barbell Curl", "Overhand Barbell Curl"],
        instructions: "Curl the barbell with an overhand grip, keeping the wrists neutral and elbows pinned.",
    },
    {
        name: "Reverse EZ Bar Curl",
        muscleGroup: "Biceps",
        equipment: "EZ Bar",
        movementType: "Curl",
        primaryMuscles: ["brachialis", "forearms"],
        secondaryMuscles: ["biceps"],
        aliases: ["Reverse-Grip EZ Bar Curl", "Overhand EZ Bar Curl"],
    },
    {
        name: "Drag Curl",
        muscleGroup: "Biceps",
        equipment: "Barbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Barbell Drag Curl"],
        instructions: "Curl the bar while dragging it up the torso and driving the elbows back, then lower slowly.",
    },
    {
        name: "Barbell Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Barbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: [],
        instructions: "With upper arms on a preacher bench, curl a straight bar from full extension to the shoulders.",
    },
    {
        name: "EZ Bar Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "EZ Bar",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Preacher Curl", "EZ Preacher Curl", "EZ-Bar Preacher Curl"],
        instructions: "With upper arms on a preacher pad, curl an EZ bar from full extension without lifting the elbows.",
    },
    {
        name: "Barbell Spider Curl",
        muscleGroup: "Biceps",
        equipment: "Barbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: [],
    },
    {
        name: "EZ Bar Spider Curl",
        muscleGroup: "Biceps",
        equipment: "EZ Bar",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Spider Curl", "EZ Spider Curl"],
        instructions: "Lie chest-down on an incline bench and curl an EZ bar with the arms hanging free, squeezing at the top.",
    },
    {
        name: "21s",
        muscleGroup: "Biceps",
        equipment: "EZ Bar",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Twenty Ones", "21s Curl", "Barbell 21s"],
        instructions: "Perform 7 bottom-half curls, 7 top-half curls, then 7 full-range curls without resting between segments.",
    },

    // ── Dumbbell curls ───────────────────────────────────────────────────────
    {
        name: "Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Standing Dumbbell Curl", "DB Curl", "Bicep Curl", "Dumbbell Bicep Curl"],
        instructions: "Stand holding dumbbells at the sides with palms forward, curl both together to the shoulders, then lower under control.",
    },
    {
        name: "Alternating Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Alternating Curl", "Alt Dumbbell Curl"],
        instructions: "Curl one dumbbell at a time, alternating arms each rep while keeping the torso still.",
    },
    {
        name: "Single Arm Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Single-Arm Dumbbell Curl", "One Arm Dumbbell Curl", "One Arm Curl"],
    },
    {
        name: "Incline Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Incline Curl", "Incline DB Curl"],
        instructions: "Sit on an incline bench with arms hanging back, curl the dumbbells without swinging the shoulders forward.",
    },
    {
        name: "Alternating Incline Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Alternating Incline Curl"],
    },
    {
        name: "Single Arm Incline Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Single-Arm Incline Dumbbell Curl"],
    },
    {
        name: "Seated Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Seated Curl"],
        instructions: "Sit upright and curl both dumbbells together, keeping the upper arms still.",
    },
    {
        name: "Concentration Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Dumbbell Concentration Curl"],
        instructions: "Sit with the working elbow braced against the inner thigh and curl the dumbbell to the shoulder.",
    },
    {
        name: "Dumbbell Spider Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Spider Dumbbell Curl", "DB Spider Curl"],
        instructions: "Lie chest-down on an incline bench and curl dumbbells with the arms hanging free.",
    },
    {
        name: "Dumbbell Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["DB Preacher Curl"],
    },
    {
        name: "Single Arm Dumbbell Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Single-Arm Dumbbell Preacher Curl", "One Arm Preacher Curl"],
    },
    {
        name: "Dumbbell Drag Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["DB Drag Curl"],
    },
    {
        name: "Zottman Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps", "forearms"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Zottman Dumbbell Curl"],
        instructions: "Curl with palms up, rotate to palms down at the top, then lower with an overhand grip.",
    },
    {
        name: "Reverse Dumbbell Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["brachialis", "forearms"],
        secondaryMuscles: ["biceps"],
        aliases: ["Overhand Dumbbell Curl", "Reverse Grip Dumbbell Curl"],
    },

    // ── Hammer / neutral ─────────────────────────────────────────────────────
    {
        name: "Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Dumbbell Hammer Curl", "Neutral Grip Curl", "DB Hammer Curl"],
        instructions: "Curl the dumbbells with a neutral (thumbs-up) grip, keeping the elbows pinned to the sides.",
    },
    {
        name: "Alternating Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Alternating Dumbbell Hammer Curl"],
    },
    {
        name: "Single Arm Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Single-Arm Hammer Curl", "One Arm Hammer Curl"],
    },
    {
        name: "Cross Body Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Cross-Body Hammer Curl", "Crossbody Hammer Curl"],
        instructions: "Curl each dumbbell across the body toward the opposite shoulder with a neutral grip.",
    },
    {
        name: "Incline Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Incline Dumbbell Hammer Curl"],
    },
    {
        name: "Seated Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: [],
    },
    {
        name: "Rope Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Cable Rope Hammer Curl", "Rope Curl"],
        instructions: "Curl a cable rope with a neutral grip, keeping elbows fixed at the sides.",
    },
    {
        name: "Cable Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Neutral Grip Cable Curl"],
    },
    {
        name: "Machine Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Machine",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: [],
    },

    // ── Cable curls ──────────────────────────────────────────────────────────
    {
        name: "Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Cable Bicep Curl", "Standing Cable Curl"],
        instructions: "Stand facing a low cable, curl the handle to the shoulders with elbows fixed, then lower under control.",
    },
    {
        name: "Single Arm Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Single-Arm Cable Curl", "One Arm Cable Curl"],
    },
    {
        name: "Rope Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Cable Rope Curl"],
    },
    {
        name: "EZ Bar Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["EZ-Bar Cable Curl", "Cable EZ Bar Curl"],
    },
    {
        name: "Straight Bar Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Cable Straight Bar Curl", "Bar Cable Curl"],
    },
    {
        name: "Bayesian Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        aliases: ["Bayesian Cable Curl", "Behind Body Bayesian Curl"],
        instructions: "Face away from a low cable with the working arm slightly behind the torso and curl from a stretched position.",
    },
    {
        name: "Single Arm Bayesian Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        aliases: ["Single-Arm Bayesian Curl"],
    },
    {
        name: "Behind the Body Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        aliases: ["Behind-the-Body Cable Curl", "Behind Body Cable Curl"],
    },
    {
        name: "High Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Overhead Cable Curl", "High Pulley Curl"],
        instructions: "With cables set high, curl the handles toward the head while keeping the upper arms still.",
    },
    {
        name: "Single Arm High Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Single-Arm High Cable Curl"],
    },
    {
        name: "Lying Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Supine Cable Curl"],
    },
    {
        name: "Seated Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: [],
    },
    {
        name: "Cable Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: [],
    },
    {
        name: "Single Arm Cable Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Single-Arm Cable Preacher Curl"],
    },
    {
        name: "Cable Spider Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: [],
    },
    {
        name: "Cable Drag Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: [],
    },
    {
        name: "Reverse Cable Curl",
        muscleGroup: "Biceps",
        equipment: "Cable",
        movementType: "Curl",
        primaryMuscles: ["brachialis", "forearms"],
        secondaryMuscles: ["biceps"],
        aliases: ["Reverse Grip Cable Curl", "Overhand Cable Curl"],
    },

    // ── Machine ──────────────────────────────────────────────────────────────
    {
        name: "Machine Bicep Curl",
        muscleGroup: "Biceps",
        equipment: "Machine",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Machine Curl", "Bicep Curl Machine", "Selectorized Bicep Curl"],
        instructions: "Adjust the seat so the pads rest under the upper arms, curl through a full range, then lower under control.",
    },
    {
        name: "Machine Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Machine",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Preacher Curl Machine"],
        instructions: "Sit at the preacher machine with upper arms on the pad and curl the handles without lifting the elbows.",
    },
    {
        name: "Single Arm Machine Bicep Curl",
        muscleGroup: "Biceps",
        equipment: "Machine",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Single-Arm Machine Bicep Curl", "Single Arm Machine Curl"],
    },
    {
        name: "Single Arm Machine Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Machine",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Single-Arm Machine Preacher Curl"],
    },

    // ── Spider (remaining unilateral) ────────────────────────────────────────
    {
        name: "Single Arm Spider Curl",
        muscleGroup: "Biceps",
        equipment: "Dumbbell",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Single-Arm Spider Curl", "Single Arm Dumbbell Spider Curl"],
    },

    // ── Resistance band ──────────────────────────────────────────────────────
    {
        name: "Resistance Band Curl",
        muscleGroup: "Biceps",
        equipment: "Resistance Band",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Band Curl", "Band Bicep Curl"],
    },
    {
        name: "Single Arm Resistance Band Curl",
        muscleGroup: "Biceps",
        equipment: "Resistance Band",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis", "forearms"],
        aliases: ["Single-Arm Band Curl", "Single Arm Band Curl"],
    },
    {
        name: "Resistance Band Hammer Curl",
        muscleGroup: "Biceps",
        equipment: "Resistance Band",
        movementType: "Neutral Grip Curl",
        primaryMuscles: ["brachialis"],
        secondaryMuscles: ["biceps", "forearms"],
        aliases: ["Band Hammer Curl"],
    },
    {
        name: "Resistance Band Preacher Curl",
        muscleGroup: "Biceps",
        equipment: "Resistance Band",
        movementType: "Curl",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["brachialis"],
        aliases: ["Band Preacher Curl"],
    },
];

/**
 * Identity-key aliases (must match exerciseIdentityKey normalisation).
 */
const BICEPS_KEY_ALIASES = {
    // Barbell / EZ
    "barbell bicep curl": "barbell curl",
    "bb curl": "barbell curl",
    "standing barbell curl": "barbell curl",
    "ez bar curl": "ez bar curl",
    "ez curl": "ez bar curl",
    "easy bar curl": "ez bar curl",
    "wide grip curl": "wide grip barbell curl",
    "close grip curl": "close grip barbell curl",
    "reverse grip barbell curl": "reverse barbell curl",
    "overhand barbell curl": "reverse barbell curl",
    "reverse grip ez bar curl": "reverse ez bar curl",
    "overhand ez bar curl": "reverse ez bar curl",
    "barbell drag curl": "drag curl",
    "preacher curl": "ez bar preacher curl",
    "ez preacher curl": "ez bar preacher curl",
    "spider curl": "ez bar spider curl",
    "ez spider curl": "ez bar spider curl",
    "twenty one": "21",
    "twenty ones": "21",
    "21 curl": "21",
    "21s curl": "21",
    "barbell 21": "21",

    // Dumbbell
    "standing dumbbell curl": "dumbbell curl",
    "db curl": "dumbbell curl",
    "bicep curl": "dumbbell curl",
    "dumbbell bicep curl": "dumbbell curl",
    "alternating curl": "alternating dumbbell curl",
    "alt dumbbell curl": "alternating dumbbell curl",
    "one arm dumbbell curl": "single arm dumbbell curl",
    "one arm curl": "single arm dumbbell curl",
    "incline curl": "incline dumbbell curl",
    "incline db curl": "incline dumbbell curl",
    "alternating incline curl": "alternating incline dumbbell curl",
    "seated curl": "seated dumbbell curl",
    "dumbbell concentration curl": "concentration curl",
    "spider dumbbell curl": "dumbbell spider curl",
    "db spider curl": "dumbbell spider curl",
    "db preacher curl": "dumbbell preacher curl",
    "one arm preacher curl": "single arm dumbbell preacher curl",
    "db drag curl": "dumbbell drag curl",
    "zottman dumbbell curl": "zottman curl",
    "overhand dumbbell curl": "reverse dumbbell curl",
    "reverse grip dumbbell curl": "reverse dumbbell curl",

    // Hammer
    "dumbbell hammer curl": "hammer curl",
    "neutral grip curl": "hammer curl",
    "db hammer curl": "hammer curl",
    "alternating dumbbell hammer curl": "alternating hammer curl",
    "one arm hammer curl": "single arm hammer curl",
    "cross body hammer curl": "cross body hammer curl",
    "crossbody hammer curl": "cross body hammer curl",
    "incline dumbbell hammer curl": "incline hammer curl",
    "cable rope hammer curl": "rope hammer curl",
    "rope curl": "rope hammer curl",
    "neutral grip cable curl": "cable hammer curl",

    // Cable
    "cable bicep curl": "cable curl",
    "standing cable curl": "cable curl",
    "one arm cable curl": "single arm cable curl",
    "cable rope curl": "rope cable curl",
    "cable ez bar curl": "ez bar cable curl",
    "cable straight bar curl": "straight bar cable curl",
    "bar cable curl": "straight bar cable curl",
    "bayesian cable curl": "bayesian curl",
    "behind body bayesian curl": "bayesian curl",
    "behind body cable curl": "behind the body cable curl",
    "overhead cable curl": "high cable curl",
    "high pulley curl": "high cable curl",
    "supine cable curl": "lying cable curl",
    "reverse grip cable curl": "reverse cable curl",
    "overhand cable curl": "reverse cable curl",

    // Machine
    "machine curl": "machine bicep curl",
    "bicep curl machine": "machine bicep curl",
    "selectorized bicep curl": "machine bicep curl",
    "preacher curl machine": "machine preacher curl",
    "single arm machine curl": "single arm machine bicep curl",

    // Spider / band
    "single arm dumbbell spider curl": "single arm spider curl",
    "band curl": "resistance band curl",
    "band bicep curl": "resistance band curl",
    "single arm band curl": "single arm resistance band curl",
    "band hammer curl": "resistance band hammer curl",
    "band preacher curl": "resistance band preacher curl",
};

function bicepsDictionaryEntries() {
    return BICEPS_CATALOG.map((entry) => ({
        name: entry.name,
        muscleGroup: entry.muscleGroup,
        ...(entry.instructions ? { instructions: entry.instructions } : {}),
    }));
}

function bicepsSearchAliasRows() {
    const rows = [];
    for (const entry of BICEPS_CATALOG) {
        for (const alias of entry.aliases ?? []) {
            rows.push({
                alias,
                name: entry.name,
                muscleGroup: entry.muscleGroup,
            });
        }
    }
    return rows;
}

function bicepsMergeTargets() {
    return BICEPS_CATALOG.map((entry) => ({
        targetName: entry.name,
        targetMuscleGroup: entry.muscleGroup,
        sourceNames: [...new Set([...(entry.aliases ?? [])])],
    })).filter((row) => row.sourceNames.length > 0);
}

module.exports = {
    BICEPS_CATALOG,
    BICEPS_KEY_ALIASES,
    bicepsDictionaryEntries,
    bicepsSearchAliasRows,
    bicepsMergeTargets,
};
