/**
 * Canonical Chest exercise catalog.
 *
 * Architecture (reusable for Back, Shoulders, … later):
 * - `name` is the only GlobalExercise row we seed
 * - `aliases` are search + identity synonyms; never separate DB rows
 * - Migration remaps historical plan/log names onto `name` via mergeExercisesIntoTarget
 *
 * Identity keys use the same normalisation as `exerciseIdentityKey`
 * (lowercase, singularised, compounds split) — see CHEST_KEY_ALIASES.
 */

/** @typedef {{
 *   name: string,
 *   muscleGroup: "Chest",
 *   equipment: string,
 *   movementType: "Press" | "Fly" | "Dip" | "Push-Up" | "Other",
 *   primaryMuscles: string[],
 *   secondaryMuscles: string[],
 *   aliases?: string[],
 *   instructions?: string,
 * }} ChestCatalogEntry */

/** @type {ChestCatalogEntry[]} */
const CHEST_CATALOG = [
    // ── Barbell ──────────────────────────────────────────────────────────────
    {
        name: "Barbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Bench Press", "Flat Bench Press", "BB Bench Press", "Flat Barbell Bench Press"],
        instructions: "Lie on a flat bench, unrack the bar above mid-chest, lower with control, then press to lockout.",
    },
    {
        name: "Incline Barbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Incline Bench Press", "Incline BB Bench Press"],
        instructions: "Set the bench to a moderate incline. Press from upper chest to lockout.",
    },
    {
        name: "Decline Barbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Decline Bench Press", "Decline BB Bench Press"],
        instructions: "Secure your legs on a decline bench and press from lower chest.",
    },
    {
        name: "Close Grip Barbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Close Grip Bench Press", "Close-Grip Bench Press", "Close-Grip Barbell Bench Press"],
        instructions: "Use a narrower grip than a standard bench press; keep elbows closer to the torso.",
    },
    {
        name: "Wide Grip Barbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Wide Grip Bench Press", "Wide-Grip Bench Press"],
        instructions: "Take a wider-than-shoulder grip and press with elbows flared moderately.",
    },
    {
        name: "Paused Barbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Paused Bench Press", "Pause Bench Press"],
        instructions: "Lower to the chest, pause motionless on the torso, then press explosively.",
    },
    {
        name: "Spoto Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Spoto Bench Press"],
        instructions: "Pause the bar just above the chest without touching, then press.",
    },
    {
        name: "Larsen Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: [],
        instructions: "Bench press with feet elevated or legs straight to remove leg drive.",
    },
    {
        name: "Barbell Floor Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        aliases: ["Floor Press", "BB Floor Press"],
        instructions: "Press from the floor; upper arms rest on the ground at the bottom.",
    },
    {
        name: "Guillotine Press",
        muscleGroup: "Chest",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Guillotine Bench Press", "Neck Press"],
        instructions: "Lower the bar toward the neck/upper chest with a controlled path — use lighter loads.",
    },

    // ── Dumbbell ─────────────────────────────────────────────────────────────
    {
        name: "Dumbbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["DB Bench Press", "Flat Dumbbell Bench Press", "Dumbbell Flat Bench Press"],
    },
    {
        name: "Incline Dumbbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Incline Dumbbell Press", "Incline DB Bench Press", "Incline DB Press"],
    },
    {
        name: "Decline Dumbbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Decline Dumbbell Press", "Decline DB Bench Press"],
    },
    {
        name: "Neutral Grip Dumbbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        aliases: ["Neutral Grip DB Bench Press", "Hammer Grip Dumbbell Bench Press"],
    },
    {
        name: "Incline Neutral Grip Dumbbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Incline Neutral Grip Dumbbell Press"],
    },
    {
        name: "Single Arm Dumbbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Single-Arm Dumbbell Bench Press", "One Arm Dumbbell Bench Press"],
    },
    {
        name: "Single Arm Incline Dumbbell Bench Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Single-Arm Incline Dumbbell Bench Press", "Single Arm Incline Dumbbell Press"],
    },
    {
        name: "Dumbbell Floor Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        aliases: ["DB Floor Press"],
    },
    {
        name: "Dumbbell Chest Fly",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: [
            "Chest Fly",
            "Dumbbell Fly",
            "Flat Dumbbell Fly",
            "Flat Dumbbell Chest Fly",
            "DB Chest Fly",
            "DB Fly",
        ],
    },
    {
        name: "Incline Dumbbell Chest Fly",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Incline Dumbbell Fly", "Incline DB Fly", "Incline Chest Fly"],
    },
    {
        name: "Decline Dumbbell Chest Fly",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Decline Dumbbell Fly", "Decline DB Fly"],
    },
    {
        name: "Dumbbell Squeeze Press",
        muscleGroup: "Chest",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        aliases: ["Squeeze Press", "Hex Press"],
    },

    // ── Smith Machine ────────────────────────────────────────────────────────
    {
        name: "Smith Machine Bench Press",
        muscleGroup: "Chest",
        equipment: "Smith Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Smith Bench Press"],
    },
    {
        name: "Smith Machine Incline Bench Press",
        muscleGroup: "Chest",
        equipment: "Smith Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Smith Machine Incline Press", "Smith Incline Bench Press"],
    },
    {
        name: "Smith Machine Decline Bench Press",
        muscleGroup: "Chest",
        equipment: "Smith Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Smith Machine Decline Press"],
    },
    {
        name: "Smith Machine Close Grip Bench Press",
        muscleGroup: "Chest",
        equipment: "Smith Machine",
        movementType: "Press",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Smith Close Grip Bench Press"],
    },

    // ── Machines ─────────────────────────────────────────────────────────────
    {
        name: "Machine Chest Press",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Chest Press Machine", "Seated Chest Press"],
    },
    {
        name: "Incline Machine Chest Press",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Incline Machine Press", "Incline Chest Press Machine"],
    },
    {
        name: "Decline Machine Chest Press",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Decline Machine Press"],
    },
    {
        name: "Plate Loaded Chest Press",
        muscleGroup: "Chest",
        equipment: "Plate Loaded Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Plate-Loaded Chest Press"],
    },
    {
        name: "Plate Loaded Incline Chest Press",
        muscleGroup: "Chest",
        equipment: "Plate Loaded Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Plate-Loaded Incline Chest Press"],
    },
    {
        name: "Plate Loaded Decline Chest Press",
        muscleGroup: "Chest",
        equipment: "Plate Loaded Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Plate-Loaded Decline Chest Press"],
    },
    {
        name: "Converging Chest Press",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Converging Machine Chest Press"],
    },
    {
        name: "Incline Converging Chest Press",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: [],
    },
    {
        name: "Single Arm Machine Chest Press",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Single-Arm Machine Chest Press"],
    },
    {
        name: "Single Arm Incline Machine Chest Press",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Single-Arm Incline Machine Chest Press"],
    },

    // ── Cable presses ────────────────────────────────────────────────────────
    {
        name: "Cable Chest Press",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Standing Cable Chest Press", "Cable Press"],
    },
    {
        name: "Incline Cable Chest Press",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Incline Cable Press"],
    },
    {
        name: "Decline Cable Chest Press",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Decline Cable Press"],
    },
    {
        name: "Single Arm Cable Chest Press",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Single-Arm Cable Chest Press"],
    },
    {
        name: "Single Arm Incline Cable Chest Press",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Single-Arm Incline Cable Chest Press"],
    },

    // ── Cable flys ───────────────────────────────────────────────────────────
    {
        name: "Cable Chest Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Cable Fly", "Standing Cable Fly", "Cable Crossover", "Mid Cable Fly"],
        instructions: "Set pulleys at mid-chest height and bring the handles together in a wide arc.",
    },
    {
        name: "Low to High Cable Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Low Cable Fly", "Low-to-High Cable Fly", "Cable Low to High Fly"],
        instructions: "Start with pulleys low and sweep the handles upward to meet at upper-chest height.",
    },
    {
        name: "High to Low Cable Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["High Cable Fly", "High-to-Low Cable Fly", "Cable High to Low Fly"],
        instructions: "Start with pulleys high and sweep the handles downward to meet at lower-chest height.",
    },
    {
        name: "Single Arm Cable Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "core"],
        aliases: ["Single-Arm Cable Fly"],
    },
    {
        name: "Single Arm Low to High Cable Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "core"],
        aliases: ["Single-Arm Low to High Cable Fly"],
    },
    {
        name: "Single Arm High to Low Cable Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "core"],
        aliases: ["Single-Arm High to Low Cable Fly"],
    },
    {
        name: "Seated Cable Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: [],
    },
    {
        name: "Incline Cable Fly",
        muscleGroup: "Chest",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Incline Cable Chest Fly"],
    },

    // ── Pec deck / machine fly ───────────────────────────────────────────────
    {
        name: "Pec Deck Fly",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Pec Deck", "Pec Deck Machine", "Butterfly Machine"],
    },
    {
        name: "Machine Chest Fly",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Machine Fly", "Chest Fly Machine"],
    },
    {
        name: "Single Arm Pec Deck Fly",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Single-Arm Pec Deck Fly"],
    },
    {
        name: "Single Arm Machine Chest Fly",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Single-Arm Machine Chest Fly"],
    },

    // ── Dips ─────────────────────────────────────────────────────────────────
    {
        name: "Chest Dip",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Dip",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        aliases: ["Dips Chest", "Chest Dips"],
    },
    {
        name: "Weighted Chest Dip",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Dip",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        aliases: ["Weighted Dip", "Weighted Chest Dips"],
    },
    {
        name: "Assisted Chest Dip",
        muscleGroup: "Chest",
        equipment: "Machine",
        movementType: "Dip",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        aliases: ["Assisted Dip", "Machine Assisted Chest Dip"],
    },

    // ── Push-ups ─────────────────────────────────────────────────────────────
    {
        name: "Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Pushup", "Push Up", "Push-Ups", "Pushups"],
    },
    {
        name: "Incline Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Incline Pushup"],
    },
    {
        name: "Decline Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Decline Pushup"],
    },
    {
        name: "Deficit Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Deficit Pushup"],
    },
    {
        name: "Diamond Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Diamond Pushup", "Triangle Push-Up"],
    },
    {
        name: "Wide Grip Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Wide Push-Up", "Wide Pushup", "Wide-Grip Push-Up"],
    },
    {
        name: "Close Grip Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Close-Grip Push-Up", "Close Push-Up"],
    },
    {
        name: "Archer Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Archer Pushup"],
    },
    {
        name: "Ring Push-Up",
        muscleGroup: "Chest",
        equipment: "Rings",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Ring Pushup", "Gymnastic Ring Push-Up"],
    },
    {
        name: "Weighted Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Weighted Pushup"],
    },
    {
        name: "Resistance Band Push-Up",
        muscleGroup: "Chest",
        equipment: "Resistance Band",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Banded Push-Up", "Band Push-Up"],
    },
    {
        name: "Plyometric Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Plyo Push-Up", "Explosive Push-Up"],
    },
    {
        name: "Clap Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Clapping Push-Up"],
    },
    {
        name: "One Arm Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["One-Arm Push-Up", "Single Arm Push-Up"],
    },
    {
        name: "Knee Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Kneeling Push-Up", "Knee Pushup"],
    },
    {
        name: "Wall Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Wall Pushup", "Wall Push Up"],
    },
    {
        name: "Hand Release Push-Up",
        muscleGroup: "Chest",
        equipment: "Bodyweight",
        movementType: "Push-Up",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Hand-Release Push-Up"],
    },

    // ── Other ────────────────────────────────────────────────────────────────
    {
        name: "Svend Press",
        muscleGroup: "Chest",
        equipment: "Plate",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Plate Squeeze Press"],
    },
    {
        name: "Landmine Chest Press",
        muscleGroup: "Chest",
        equipment: "Landmine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Landmine Press", "Standing Landmine Chest Press"],
    },
    {
        name: "Single Arm Landmine Chest Press",
        muscleGroup: "Chest",
        equipment: "Landmine",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Single-Arm Landmine Chest Press", "Single Arm Landmine Press"],
    },
    {
        name: "Resistance Band Chest Press",
        muscleGroup: "Chest",
        equipment: "Resistance Band",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        aliases: ["Band Chest Press"],
    },
    {
        name: "Single Arm Resistance Band Chest Press",
        muscleGroup: "Chest",
        equipment: "Resistance Band",
        movementType: "Press",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps", "core"],
        aliases: ["Single-Arm Band Chest Press"],
    },
    {
        name: "Resistance Band Chest Fly",
        muscleGroup: "Chest",
        equipment: "Resistance Band",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        aliases: ["Band Chest Fly", "Band Fly"],
    },
    {
        name: "Single Arm Resistance Band Chest Fly",
        muscleGroup: "Chest",
        equipment: "Resistance Band",
        movementType: "Fly",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "core"],
        aliases: ["Single-Arm Band Chest Fly"],
    },
];

/**
 * Maps normalised identity keys of aliases → canonical identity key.
 * Keys must match `exerciseIdentityKey` output (see exerciseIdentity.ts).
 */
const CHEST_KEY_ALIASES = {
    // Barbell
    "bench press": "barbell bench press",
    "flat bench press": "barbell bench press",
    "bb bench press": "barbell bench press",
    "flat barbell bench press": "barbell bench press",
    "incline bench press": "incline barbell bench press",
    "incline bb bench press": "incline barbell bench press",
    "decline bench press": "decline barbell bench press",
    "decline bb bench press": "decline barbell bench press",
    "close grip bench press": "close grip barbell bench press",
    "close grip barbell bench press": "close grip barbell bench press",
    "wide grip bench press": "wide grip barbell bench press",
    "paused bench press": "paused barbell bench press",
    "pause bench press": "paused barbell bench press",
    "spoto bench press": "spoto press",
    "floor press": "barbell floor press",
    "bb floor press": "barbell floor press",
    "guillotine bench press": "guillotine press",
    "neck press": "guillotine press",

    // Dumbbell
    "db bench press": "dumbbell bench press",
    "flat dumbbell bench press": "dumbbell bench press",
    "dumbbell flat bench press": "dumbbell bench press",
    "incline dumbbell press": "incline dumbbell bench press",
    "incline db bench press": "incline dumbbell bench press",
    "incline db press": "incline dumbbell bench press",
    "decline dumbbell press": "decline dumbbell bench press",
    "decline db bench press": "decline dumbbell bench press",
    "neutral grip db bench press": "neutral grip dumbbell bench press",
    "hammer grip dumbbell bench press": "neutral grip dumbbell bench press",
    "incline neutral grip dumbbell press": "incline neutral grip dumbbell bench press",
    "one arm dumbbell bench press": "single arm dumbbell bench press",
    "single arm incline dumbbell press": "single arm incline dumbbell bench press",
    "db floor press": "dumbbell floor press",
    "chest fly": "dumbbell chest fly",
    "dumbbell fly": "dumbbell chest fly",
    "flat dumbbell fly": "dumbbell chest fly",
    "flat dumbbell chest fly": "dumbbell chest fly",
    "db chest fly": "dumbbell chest fly",
    "db fly": "dumbbell chest fly",
    "incline dumbbell fly": "incline dumbbell chest fly",
    "incline db fly": "incline dumbbell chest fly",
    "incline chest fly": "incline dumbbell chest fly",
    "decline dumbbell fly": "decline dumbbell chest fly",
    "decline db fly": "decline dumbbell chest fly",
    "squeeze press": "dumbbell squeeze press",
    "hex press": "dumbbell squeeze press",

    // Smith
    "smith bench press": "smith machine bench press",
    "smith machine incline press": "smith machine incline bench press",
    "smith incline bench press": "smith machine incline bench press",
    "smith machine decline press": "smith machine decline bench press",
    "smith close grip bench press": "smith machine close grip bench press",

    // Machines
    "chest press machine": "machine chest press",
    "seated chest press": "machine chest press",
    "incline machine press": "incline machine chest press",
    "incline chest press machine": "incline machine chest press",
    "decline machine press": "decline machine chest press",
    "plate loaded chest press": "plate loaded chest press",
    "converging machine chest press": "converging chest press",

    // Cable press / fly
    "standing cable chest press": "cable chest press",
    "cable press": "cable chest press",
    "incline cable press": "incline cable chest press",
    "decline cable press": "decline cable chest press",
    "cable fly": "cable chest fly",
    "standing cable fly": "cable chest fly",
    "cable crossover": "cable chest fly",
    "mid cable fly": "cable chest fly",
    "low cable fly": "low to high cable fly",
    "low to high cable fly": "low to high cable fly",
    "cable low to high fly": "low to high cable fly",
    "high cable fly": "high to low cable fly",
    "high to low cable fly": "high to low cable fly",
    "cable high to low fly": "high to low cable fly",
    "incline cable chest fly": "incline cable fly",

    // Pec deck
    "pec deck": "pec deck fly",
    "pec deck machine": "pec deck fly",
    "butterfly machine": "pec deck fly",
    "machine fly": "machine chest fly",
    "chest fly machine": "machine chest fly",

    // Dips
    "dips chest": "chest dip",
    "chest dips": "chest dip",
    "weighted dip": "weighted chest dip",
    "weighted chest dips": "weighted chest dip",
    "assisted dip": "assisted chest dip",
    "machine assisted chest dip": "assisted chest dip",

    // Push-ups
    "pushup": "push up",
    "push ups": "push up",
    "pushups": "push up",
    "incline pushup": "incline push up",
    "decline pushup": "decline push up",
    "deficit pushup": "deficit push up",
    "diamond pushup": "diamond push up",
    "triangle push up": "diamond push up",
    "wide push up": "wide grip push up",
    "wide pushup": "wide grip push up",
    "wide grip push up": "wide grip push up",
    "close push up": "close grip push up",
    "close grip push up": "close grip push up",
    "archer pushup": "archer push up",
    "ring pushup": "ring push up",
    "gymnastic ring push up": "ring push up",
    "weighted pushup": "weighted push up",
    "banded push up": "resistance band push up",
    "band push up": "resistance band push up",
    "plyo push up": "plyometric push up",
    "explosive push up": "plyometric push up",
    "clapping push up": "clap push up",
    "one arm push up": "one arm push up",
    "single arm push up": "one arm push up",
    "kneeling push up": "knee push up",
    "knee pushup": "knee push up",
    "wall pushup": "wall push up",
    "wall push up": "wall push up",
    "hand release push up": "hand release push up",

    // Other
    "plate squeeze press": "svend press",
    "landmine press": "landmine chest press",
    "standing landmine chest press": "landmine chest press",
    "single arm landmine press": "single arm landmine chest press",
    "band chest press": "resistance band chest press",
    "single arm band chest press": "single arm resistance band chest press",
    "band chest fly": "resistance band chest fly",
    "band fly": "resistance band chest fly",
    "single arm band chest fly": "single arm resistance band chest fly",
};

/** Seed rows: canonical name + muscle group (+ optional instructions). */
function chestDictionaryEntries() {
    return CHEST_CATALOG.map((entry) => ({
        name: entry.name,
        muscleGroup: entry.muscleGroup,
        ...(entry.instructions ? { instructions: entry.instructions } : {}),
    }));
}

/** Alias → canonical display name (for search expansion). */
function chestAliasToCanonicalName() {
    const map = new Map();
    for (const entry of CHEST_CATALOG) {
        map.set(entry.name.toLowerCase(), entry.name);
        for (const alias of entry.aliases ?? []) {
            map.set(alias.toLowerCase(), entry.name);
        }
    }
    return map;
}

/** Flat list of {canonicalName, alias} for search scoring. */
function chestSearchAliasRows() {
    const rows = [];
    for (const entry of CHEST_CATALOG) {
        for (const alias of entry.aliases ?? []) {
            rows.push({
                alias,
                name: entry.name,
                muscleGroup: entry.muscleGroup,
            });
        }
    }
    return rows;
}

/**
 * Historical names that should merge into each canonical entry.
 * Includes current DB duplicates not necessarily listed as search aliases.
 */
function chestMergeTargets() {
    return CHEST_CATALOG.map((entry) => ({
        targetName: entry.name,
        targetMuscleGroup: entry.muscleGroup,
        sourceNames: [...new Set([...(entry.aliases ?? [])])],
    })).filter((row) => row.sourceNames.length > 0);
}

module.exports = {
    CHEST_CATALOG,
    CHEST_KEY_ALIASES,
    chestDictionaryEntries,
    chestAliasToCanonicalName,
    chestSearchAliasRows,
    chestMergeTargets,
};
