/**
 * Canonical Shoulders exercise catalog.
 *
 * Same architecture as Chest/Back:
 * - `name` is the only GlobalExercise row we seed
 * - `aliases` are search + identity synonyms; never separate DB rows
 * - Migration remaps history via mergeExercisesIntoTarget
 *
 * primaryMuscles uses anatomy labels for metadata (frontDelts / sideDelts / rearDelts).
 * The muscle map currently resolves these via exerciseMuscles overrides → "shoulders".
 */

/** @typedef {{
 *   name: string,
 *   muscleGroup: "Shoulders",
 *   equipment: string,
 *   movementType: string,
 *   primaryMuscles: string[],
 *   secondaryMuscles: string[],
 *   aliases?: string[],
 *   instructions?: string,
 * }} ShoulderCatalogEntry */

/** @type {ShoulderCatalogEntry[]} */
const SHOULDERS_CATALOG = [
    // ── Barbell presses ──────────────────────────────────────────────────────
    {
        name: "Barbell Overhead Press",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "upperChest", "traps", "core"],
        aliases: [
            "Overhead Press",
            "Military Press",
            "OHP",
            "Barbell Shoulder Press",
            "Standing Barbell Overhead Press",
            "Strict Press",
            "Standing Military Press",
        ],
        instructions:
            "Stand with the bar at the front rack, brace, press overhead to lockout without using leg drive, then lower to the shoulders.",
    },
    {
        name: "Seated Barbell Overhead Press",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "traps"],
        aliases: ["Seated Military Press", "Seated Barbell Shoulder Press"],
        instructions: "Sit upright with back support if available and press the bar from the front rack to lockout overhead.",
    },
    {
        name: "Behind the Neck Press",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts", "sideDelts"],
        secondaryMuscles: ["triceps", "traps"],
        aliases: ["Behind-the-Neck Press", "Behind Neck Press", "BTN Press"],
        instructions: "From a high-bar rack position behind the head, press the bar overhead and return behind the neck with control.",
    },
    {
        name: "Bradford Press",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts", "sideDelts"],
        secondaryMuscles: ["triceps", "traps"],
        aliases: [],
        instructions:
            "Press the bar from the front rack just high enough to clear the head, lower behind the neck, then reverse — continuous front-to-back presses without full lockout.",
    },
    {
        name: "Push Press",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "quads", "glutes", "core"],
        aliases: ["Barbell Push Press"],
        instructions: "Dip the knees slightly, drive up through the legs, and press the bar overhead, finishing with locked elbows.",
    },
    {
        name: "Barbell Z Press",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Z Press", "Seated Floor Barbell Press"],
        instructions: "Sit on the floor with legs straight, press the bar from the front rack overhead while keeping the torso tall.",
    },
    {
        name: "Barbell Shoulder Press from Pins",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps"],
        aliases: ["Pin Press Overhead", "Overhead Press from Pins"],
        instructions: "Set the bar on rack pins at about shoulder height and press each rep from a dead stop to lockout.",
    },

    // ── Dumbbell presses ─────────────────────────────────────────────────────
    {
        name: "Seated Dumbbell Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps"],
        aliases: [
            "Dumbbell Shoulder Press",
            "Seated Dumbbell Press",
            "Seated DB Shoulder Press",
            "Dumbbell Press",
            "DB Shoulder Press",
        ],
        instructions: "Sit upright holding dumbbells at shoulder height and press them overhead to lockout, then lower with control.",
    },
    {
        name: "Standing Dumbbell Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Standing Dumbbell Press", "Standing DB Shoulder Press"],
        instructions: "Stand tall with dumbbells at the shoulders and press overhead without excessive leg drive.",
    },
    {
        name: "Neutral Grip Dumbbell Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps"],
        aliases: ["Neutral-Grip Dumbbell Shoulder Press", "Hammer Grip Dumbbell Shoulder Press"],
        instructions: "Press dumbbells overhead with palms facing each other throughout the movement.",
    },
    {
        name: "Single Arm Dumbbell Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Single-Arm Dumbbell Shoulder Press", "One Arm Dumbbell Shoulder Press"],
        instructions: "Press one dumbbell overhead while bracing the torso against rotation; repeat on both sides.",
    },
    {
        name: "Seated Single Arm Dumbbell Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Seated Single-Arm Dumbbell Shoulder Press"],
    },
    {
        name: "Arnold Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts", "sideDelts"],
        secondaryMuscles: ["triceps"],
        aliases: ["Arnold Dumbbell Press", "Seated Arnold Press"],
        instructions:
            "Start with palms facing you at shoulder height, rotate the palms out as you press overhead, then reverse on the way down.",
    },
    {
        name: "Single Arm Arnold Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts", "sideDelts"],
        secondaryMuscles: ["triceps", "core"],
        aliases: ["Single-Arm Arnold Press"],
    },
    {
        name: "Dumbbell Z Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["DB Z Press"],
        instructions: "Sit on the floor with legs straight and press dumbbells overhead while keeping the torso braced.",
    },

    // ── Smith / machine / plate-loaded ───────────────────────────────────────
    {
        name: "Smith Machine Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Smith Machine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps"],
        aliases: ["Smith Shoulder Press", "Smith Machine Overhead Press"],
        instructions: "Sit or stand under the Smith bar at shoulder height and press the bar overhead along the fixed path.",
    },
    {
        name: "Smith Machine Behind the Neck Press",
        muscleGroup: "Shoulders",
        equipment: "Smith Machine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts", "sideDelts"],
        secondaryMuscles: ["triceps"],
        aliases: ["Smith Behind the Neck Press", "Smith Behind-the-Neck Press"],
    },
    {
        name: "Machine Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Machine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps"],
        aliases: ["Shoulder Press Machine", "Seated Machine Shoulder Press"],
        instructions: "Adjust the seat so handles start near shoulder height, press to lockout, then lower under control.",
    },
    {
        name: "Plate Loaded Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Plate Loaded",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps"],
        aliases: ["Hammer Strength Shoulder Press", "HS Shoulder Press", "Plate-Loaded Shoulder Press"],
        instructions: "Load the plate-loaded shoulder press, set the seat, and press the handles overhead.",
    },
    {
        name: "Single Arm Machine Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Machine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Single-Arm Machine Shoulder Press"],
    },
    {
        name: "Single Arm Plate Loaded Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Plate Loaded",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Single-Arm Plate Loaded Shoulder Press", "Hammer Strength Single Arm Shoulder Press"],
    },

    // ── Landmine ─────────────────────────────────────────────────────────────
    {
        name: "Landmine Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Landmine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "chest", "core"],
        aliases: ["Standing Landmine Press", "Landmine Overhead Press"],
        instructions: "Hold the end of a landmine bar at the shoulder and press up and slightly forward to lockout.",
    },
    {
        name: "Single Arm Landmine Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Landmine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Single-Arm Landmine Shoulder Press", "Single Arm Landmine Press"],
    },
    {
        name: "Half Kneeling Landmine Press",
        muscleGroup: "Shoulders",
        equipment: "Landmine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Half-Kneeling Landmine Press"],
        instructions: "From a half-kneeling stance, press the landmine up and forward while keeping the ribs down.",
    },
    {
        name: "Kneeling Landmine Press",
        muscleGroup: "Shoulders",
        equipment: "Landmine",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Tall Kneeling Landmine Press"],
    },

    // ── Lateral raises (dumbbell) ────────────────────────────────────────────
    {
        name: "Dumbbell Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Lateral Raise", "Side Raise", "Side Lateral Raise", "DB Lateral Raise"],
        instructions: "Raise the dumbbells out to the sides until roughly shoulder height, lead with the elbows, then lower slowly.",
    },
    {
        name: "Seated Dumbbell Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Seated Lateral Raise"],
    },
    {
        name: "Leaning Dumbbell Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Lean Away Dumbbell Lateral Raise"],
    },
    {
        name: "Incline Dumbbell Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Incline Lateral Raise"],
    },
    {
        name: "Single Arm Dumbbell Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Single-Arm Dumbbell Lateral Raise", "One Arm Lateral Raise"],
    },
    {
        name: "Lu Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts", "frontDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Lu Lateral Raise"],
        instructions: "Raise dumbbells in a slight forward arc to about eye level with soft elbows, emphasizing the side delts.",
    },

    // ── Lateral raises (cable / machine) ─────────────────────────────────────
    {
        name: "Cable Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Cable Side Raise"],
        instructions: "Raise the cable handle out to the side to shoulder height, then lower under control.",
    },
    {
        name: "Single Arm Cable Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Single-Arm Cable Lateral Raise", "One Arm Cable Lateral Raise", "One Arm Cable Lateral"],
    },
    {
        name: "Behind the Back Cable Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Behind-the-Back Cable Lateral Raise", "Behind Back Cable Lateral Raise"],
    },
    {
        name: "Leaning Cable Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Lean Away Cable Lateral Raise"],
    },
    {
        name: "Cuffed Cable Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Ankle Cuff Cable Lateral Raise", "Cable Cuff Lateral Raise"],
    },
    {
        name: "Cross Body Cable Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Cross-Body Cable Lateral Raise"],
    },
    {
        name: "Seated Cable Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: [],
    },
    {
        name: "Machine Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Machine",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Lateral Raise Machine"],
        instructions: "Sit in the lateral raise machine and raise the pads out to the sides until roughly shoulder height.",
    },
    {
        name: "Single Arm Machine Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Machine",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Single-Arm Machine Lateral Raise"],
    },

    // ── Front raises ─────────────────────────────────────────────────────────
    {
        name: "Dumbbell Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "chest"],
        aliases: ["Front Raise", "DB Front Raise"],
        instructions: "Raise the dumbbells forward to about shoulder height with soft elbows, then lower slowly.",
    },
    {
        name: "Alternating Dumbbell Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: ["Alternating Front Raise"],
    },
    {
        name: "Single Arm Dumbbell Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: ["Single-Arm Dumbbell Front Raise", "One Arm Front Raise"],
    },
    {
        name: "Cable Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: [],
        instructions: "Raise the cable handle forward to shoulder height, then lower under control.",
    },
    {
        name: "Single Arm Cable Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: ["Single-Arm Cable Front Raise"],
    },
    {
        name: "Rope Cable Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: ["Rope Front Raise"],
    },
    {
        name: "Plate Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Plate",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: ["Weight Plate Front Raise"],
        instructions: "Hold a weight plate at the hips and raise it forward to about shoulder height, then lower slowly.",
    },
    {
        name: "Barbell Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: [],
    },
    {
        name: "Resistance Band Front Raise",
        muscleGroup: "Shoulders",
        equipment: "Resistance Band",
        movementType: "Raise",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts"],
        aliases: ["Band Front Raise"],
    },

    // ── Rear delts ───────────────────────────────────────────────────────────
    {
        name: "Dumbbell Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack", "traps"],
        aliases: ["Rear Delt Fly", "Bent Over Rear Delt Fly", "DB Rear Delt Fly"],
        instructions: "Hinge forward and raise the dumbbells out to the sides with soft elbows, squeezing the rear delts.",
    },
    {
        name: "Seated Dumbbell Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Seated Rear Delt Fly"],
    },
    {
        name: "Chest Supported Dumbbell Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Chest-Supported Rear Delt Fly", "Chest Supported Rear Delt Fly"],
    },
    {
        name: "Incline Bench Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Incline Rear Delt Fly"],
    },
    {
        name: "Single Arm Dumbbell Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Single-Arm Dumbbell Rear Delt Fly"],
    },
    {
        name: "Dumbbell Rear Delt Row",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Row",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack", "traps"],
        aliases: ["Rear Delt Row"],
        instructions: "Hinge and row the dumbbells toward the upper chest with elbows flared, emphasizing the rear delts.",
    },
    {
        name: "Cable Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Rear Delt Cable Fly", "Cable Reverse Fly", "Standing Cable Rear Delt Fly"],
        instructions: "With cables set high or mid, open the arms out and back in a reverse-fly pattern focusing on the rear delts.",
    },
    {
        name: "Single Arm Cable Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Single-Arm Cable Rear Delt Fly"],
    },
    {
        name: "Cross Body Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Cross-Body Rear Delt Fly", "Cross Body Cable Rear Delt Fly"],
    },
    {
        name: "Bent Over Cable Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Bent-Over Cable Rear Delt Fly"],
    },
    {
        name: "Reverse Pec Deck",
        muscleGroup: "Shoulders",
        equipment: "Machine",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: [
            "Rear Delt Machine Fly",
            "Rear Delt Machine",
            "Machine Rear Delt Fly",
            "Reverse Pec Deck Fly",
            "Reverse Fly Machine",
        ],
        instructions: "Sit facing the pec deck pads (or reverse handles), open the arms back until the rear delts contract, then return.",
    },
    {
        name: "Single Arm Reverse Pec Deck",
        muscleGroup: "Shoulders",
        equipment: "Machine",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Single-Arm Reverse Pec Deck", "Single Arm Machine Rear Delt Fly"],
    },

    // ── Face pulls ───────────────────────────────────────────────────────────
    {
        name: "Face Pull",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Pull",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack", "traps", "sideDelts"],
        aliases: ["Cable Face Pull", "Rope Face Pull"],
        instructions: "Pull a rope toward the face with elbows high, externally rotating at the finish, then return with control.",
    },
    {
        name: "Single Arm Face Pull",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Pull",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack", "traps"],
        aliases: ["Single-Arm Face Pull", "Single Arm Cable Face Pull"],
    },
    {
        name: "Resistance Band Face Pull",
        muscleGroup: "Shoulders",
        equipment: "Resistance Band",
        movementType: "Pull",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack", "traps"],
        aliases: ["Band Face Pull"],
    },

    // ── Upright rows ─────────────────────────────────────────────────────────
    {
        name: "Barbell Upright Row",
        muscleGroup: "Shoulders",
        equipment: "Barbell",
        movementType: "Pull",
        primaryMuscles: ["sideDelts", "traps"],
        secondaryMuscles: ["frontDelts", "biceps"],
        aliases: ["Upright Row", "BB Upright Row"],
        instructions: "Pull the bar up along the torso to about chest height with elbows leading, then lower under control.",
    },
    {
        name: "Dumbbell Upright Row",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Pull",
        primaryMuscles: ["sideDelts", "traps"],
        secondaryMuscles: ["biceps"],
        aliases: ["DB Upright Row"],
    },
    {
        name: "Cable Upright Row",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Pull",
        primaryMuscles: ["sideDelts", "traps"],
        secondaryMuscles: ["biceps"],
        aliases: [],
        instructions: "Pull a cable bar or rope up the torso to about chest height with elbows high.",
    },
    {
        name: "Smith Machine Upright Row",
        muscleGroup: "Shoulders",
        equipment: "Smith Machine",
        movementType: "Pull",
        primaryMuscles: ["sideDelts", "traps"],
        secondaryMuscles: ["biceps"],
        aliases: ["Smith Upright Row"],
    },
    {
        name: "Single Arm Cable Upright Row",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Pull",
        primaryMuscles: ["sideDelts", "traps"],
        secondaryMuscles: ["biceps"],
        aliases: ["Single-Arm Cable Upright Row"],
    },

    // ── Y / W / Cuban / stability ────────────────────────────────────────────
    {
        name: "Dumbbell Y Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts", "frontDelts"],
        secondaryMuscles: ["traps", "upperBack"],
        aliases: ["Y Raise", "DB Y Raise"],
        instructions: "Raise the arms into a Y shape overhead or on an incline, leading with the thumbs or palms as preferred.",
    },
    {
        name: "Cable Y Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts", "frontDelts"],
        secondaryMuscles: ["traps"],
        aliases: [],
    },
    {
        name: "Incline Y Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["sideDelts", "rearDelts"],
        secondaryMuscles: ["traps", "upperBack"],
        aliases: ["Incline Dumbbell Y Raise"],
    },
    {
        name: "Prone Y Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["rearDelts", "sideDelts"],
        secondaryMuscles: ["traps", "upperBack"],
        aliases: ["Prone Dumbbell Y Raise"],
    },
    {
        name: "Machine Y Raise",
        muscleGroup: "Shoulders",
        equipment: "Machine",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: [],
    },
    {
        name: "Single Arm Cable Y Raise",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Raise",
        primaryMuscles: ["sideDelts", "frontDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Single-Arm Cable Y Raise"],
    },
    {
        name: "W Raise",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Raise",
        primaryMuscles: ["rearDelts", "sideDelts"],
        secondaryMuscles: ["traps", "upperBack"],
        aliases: ["Dumbbell W Raise"],
        instructions: "With elbows bent into a W shape, raise the arms by externally rotating and squeezing the rear delts.",
    },
    {
        name: "Cuban Press",
        muscleGroup: "Shoulders",
        equipment: "Dumbbell",
        movementType: "Rotation",
        primaryMuscles: ["rearDelts", "sideDelts"],
        secondaryMuscles: ["traps", "frontDelts"],
        aliases: ["Dumbbell Cuban Press"],
        instructions:
            "Upright-row the dumbbells to about chest height, externally rotate to a press position, then press overhead and reverse.",
    },
    {
        name: "Cable Cuban Rotation",
        muscleGroup: "Shoulders",
        equipment: "Cable",
        movementType: "Rotation",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["traps", "sideDelts"],
        aliases: ["Cuban Rotation", "Cable Cuban Press"],
    },

    // ── Bodyweight ───────────────────────────────────────────────────────────
    {
        name: "Pike Push-Up",
        muscleGroup: "Shoulders",
        equipment: "Bodyweight",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["triceps", "chest", "core"],
        aliases: ["Pike Pushup", "Pike Press"],
        instructions: "From a pike position with hips high, bend the elbows to lower the head toward the floor, then press back up.",
    },
    {
        name: "Feet Elevated Pike Push-Up",
        muscleGroup: "Shoulders",
        equipment: "Bodyweight",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["triceps", "chest", "core"],
        aliases: ["Feet-Elevated Pike Push-Up", "Elevated Pike Push-Up"],
    },
    {
        name: "Handstand Push-Up",
        muscleGroup: "Shoulders",
        equipment: "Bodyweight",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["triceps", "traps", "core"],
        aliases: ["HSPU", "Handstand Pushup"],
        instructions: "In a handstand (usually against a wall), lower the head toward the floor and press back to lockout.",
    },
    {
        name: "Wall Handstand Push-Up",
        muscleGroup: "Shoulders",
        equipment: "Bodyweight",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["triceps", "traps", "core"],
        aliases: ["Wall HSPU", "Wall-Supported Handstand Push-Up"],
    },
    {
        name: "Deficit Handstand Push-Up",
        muscleGroup: "Shoulders",
        equipment: "Bodyweight",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["triceps", "traps", "core"],
        aliases: ["Deficit HSPU"],
    },
    {
        name: "Handstand Hold",
        muscleGroup: "Shoulders",
        equipment: "Bodyweight",
        movementType: "Isometric",
        primaryMuscles: ["frontDelts", "sideDelts"],
        secondaryMuscles: ["traps", "core", "triceps"],
        aliases: ["Wall Handstand Hold", "Handstand"],
        instructions: "Hold a handstand position (freestanding or wall-supported) with locked elbows and a braced midline.",
    },
    {
        name: "Wall Walk",
        muscleGroup: "Shoulders",
        equipment: "Bodyweight",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["triceps", "core", "chest"],
        aliases: ["Wall Walks"],
        instructions: "From a plank facing away from the wall, walk the feet up the wall and the hands toward the wall into a handstand.",
    },

    // ── Resistance bands ─────────────────────────────────────────────────────
    {
        name: "Resistance Band Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Resistance Band",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps"],
        aliases: ["Band Shoulder Press"],
    },
    {
        name: "Single Arm Resistance Band Shoulder Press",
        muscleGroup: "Shoulders",
        equipment: "Resistance Band",
        movementType: "Vertical Press",
        primaryMuscles: ["frontDelts"],
        secondaryMuscles: ["sideDelts", "triceps", "core"],
        aliases: ["Single-Arm Band Shoulder Press", "Single Arm Band Shoulder Press"],
    },
    {
        name: "Resistance Band Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Resistance Band",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Band Lateral Raise"],
    },
    {
        name: "Single Arm Resistance Band Lateral Raise",
        muscleGroup: "Shoulders",
        equipment: "Resistance Band",
        movementType: "Raise",
        primaryMuscles: ["sideDelts"],
        secondaryMuscles: ["traps"],
        aliases: ["Single-Arm Band Lateral Raise", "Single Arm Band Lateral Raise"],
    },
    {
        name: "Resistance Band Rear Delt Fly",
        muscleGroup: "Shoulders",
        equipment: "Resistance Band",
        movementType: "Fly",
        primaryMuscles: ["rearDelts"],
        secondaryMuscles: ["upperBack"],
        aliases: ["Band Rear Delt Fly"],
    },
];

/**
 * Identity-key aliases (must match exerciseIdentityKey normalisation).
 */
const SHOULDERS_KEY_ALIASES = {
    // Overhead press family
    "overhead press": "barbell overhead press",
    "military press": "barbell overhead press",
    "ohp": "barbell overhead press",
    "barbell shoulder press": "barbell overhead press",
    "standing barbell overhead press": "barbell overhead press",
    "strict press": "barbell overhead press",
    "standing military press": "barbell overhead press",
    "seated military press": "seated barbell overhead press",
    "behind the neck press": "behind the neck press",
    "behind neck press": "behind the neck press",
    "btn press": "behind the neck press",
    "z press": "barbell z press",
    "seated floor barbell press": "barbell z press",
    "pin press overhead": "barbell shoulder press from pin",
    "overhead press from pin": "barbell shoulder press from pin",

    // Dumbbell presses
    "dumbbell shoulder press": "seated dumbbell shoulder press",
    "seated dumbbell press": "seated dumbbell shoulder press",
    "seated db shoulder press": "seated dumbbell shoulder press",
    "dumbbell press": "seated dumbbell shoulder press",
    "db shoulder press": "seated dumbbell shoulder press",
    "standing dumbbell press": "standing dumbbell shoulder press",
    "neutral grip dumbbell shoulder press": "neutral grip dumbbell shoulder press",
    "hammer grip dumbbell shoulder press": "neutral grip dumbbell shoulder press",
    "one arm dumbbell shoulder press": "single arm dumbbell shoulder press",
    "arnold dumbbell press": "arnold press",
    "seated arnold press": "arnold press",
    "db z press": "dumbbell z press",

    // Machines
    "smith shoulder press": "smith machine shoulder press",
    "smith machine overhead press": "smith machine shoulder press",
    "shoulder press machine": "machine shoulder press",
    "seated machine shoulder press": "machine shoulder press",
    "hammer strength shoulder press": "plate loaded shoulder press",
    "hs shoulder press": "plate loaded shoulder press",
    "plate loaded shoulder press": "plate loaded shoulder press",

    // Landmine
    "standing landmine press": "landmine shoulder press",
    "landmine overhead press": "landmine shoulder press",
    "single arm landmine press": "single arm landmine shoulder press",
    "half kneeling landmine press": "half kneeling landmine press",
    "tall kneeling landmine press": "kneeling landmine press",

    // Lateral raises
    "lateral raise": "dumbbell lateral raise",
    "side raise": "dumbbell lateral raise",
    "side lateral raise": "dumbbell lateral raise",
    "db lateral raise": "dumbbell lateral raise",
    "seated lateral raise": "seated dumbbell lateral raise",
    "lean away dumbbell lateral raise": "leaning dumbbell lateral raise",
    "incline lateral raise": "incline dumbbell lateral raise",
    "one arm lateral raise": "single arm dumbbell lateral raise",
    "lu lateral raise": "lu raise",
    "cable side raise": "cable lateral raise",
    "one arm cable lateral raise": "single arm cable lateral raise",
    "one arm cable lateral": "single arm cable lateral raise",
    "behind back cable lateral raise": "behind the back cable lateral raise",
    "lean away cable lateral raise": "leaning cable lateral raise",
    "ankle cuff cable lateral raise": "cuffed cable lateral raise",
    "cable cuff lateral raise": "cuffed cable lateral raise",
    "lateral raise machine": "machine lateral raise",

    // Front raises
    "front raise": "dumbbell front raise",
    "db front raise": "dumbbell front raise",
    "alternating front raise": "alternating dumbbell front raise",
    "one arm front raise": "single arm dumbbell front raise",
    "rope front raise": "rope cable front raise",
    "weight plate front raise": "plate front raise",
    "band front raise": "resistance band front raise",

    // Rear delts
    "rear delt fly": "dumbbell rear delt fly",
    "bent over rear delt fly": "dumbbell rear delt fly",
    "db rear delt fly": "dumbbell rear delt fly",
    "seated rear delt fly": "seated dumbbell rear delt fly",
    "chest supported rear delt fly": "chest supported dumbbell rear delt fly",
    "incline rear delt fly": "incline bench rear delt fly",
    "rear delt row": "dumbbell rear delt row",
    "rear delt cable fly": "cable rear delt fly",
    "cable reverse fly": "cable rear delt fly",
    "standing cable rear delt fly": "cable rear delt fly",
    "cross body cable rear delt fly": "cross body rear delt fly",
    "rear delt machine fly": "reverse pec deck",
    "rear delt machine": "reverse pec deck",
    "machine rear delt fly": "reverse pec deck",
    "reverse pec deck fly": "reverse pec deck",
    "reverse fly machine": "reverse pec deck",
    "single arm machine rear delt fly": "single arm reverse pec deck",

    // Face pulls
    "cable face pull": "face pull",
    "rope face pull": "face pull",
    "single arm cable face pull": "single arm face pull",
    "band face pull": "resistance band face pull",

    // Upright rows
    "upright row": "barbell upright row",
    "bb upright row": "barbell upright row",
    "db upright row": "dumbbell upright row",
    "smith upright row": "smith machine upright row",

    // Y / W / Cuban
    "y raise": "dumbbell y raise",
    "db y raise": "dumbbell y raise",
    "incline dumbbell y raise": "incline y raise",
    "prone dumbbell y raise": "prone y raise",
    "dumbbell w raise": "w raise",
    "dumbbell cuban press": "cuban press",
    "cuban rotation": "cable cuban rotation",
    "cable cuban press": "cable cuban rotation",

    // Bodyweight
    "pike pushup": "pike push up",
    "pike press": "pike push up",
    "feet elevated pike push up": "feet elevated pike push up",
    "hspu": "handstand push up",
    "handstand pushup": "handstand push up",
    "wall hspu": "wall handstand push up",
    "wall supported handstand push up": "wall handstand push up",
    "deficit hspu": "deficit handstand push up",
    "wall handstand hold": "handstand hold",
    "handstand": "handstand hold",
    "wall walks": "wall walk",

    // Bands
    "band shoulder press": "resistance band shoulder press",
    "single arm band shoulder press": "single arm resistance band shoulder press",
    "band lateral raise": "resistance band lateral raise",
    "single arm band lateral raise": "single arm resistance band lateral raise",
    "band rear delt fly": "resistance band rear delt fly",
};

function shouldersDictionaryEntries() {
    return SHOULDERS_CATALOG.map((entry) => ({
        name: entry.name,
        muscleGroup: entry.muscleGroup,
        ...(entry.instructions ? { instructions: entry.instructions } : {}),
    }));
}

function shouldersSearchAliasRows() {
    const rows = [];
    for (const entry of SHOULDERS_CATALOG) {
        for (const alias of entry.aliases ?? []) {
            rows.push({
                alias,
                name: entry.name,
                muscleGroup: entry.muscleGroup,
            });
        }
    }
    return rows;
}

function shouldersMergeTargets() {
    return SHOULDERS_CATALOG.map((entry) => ({
        targetName: entry.name,
        targetMuscleGroup: entry.muscleGroup,
        sourceNames: [...new Set([...(entry.aliases ?? [])])],
    })).filter((row) => row.sourceNames.length > 0);
}

module.exports = {
    SHOULDERS_CATALOG,
    SHOULDERS_KEY_ALIASES,
    shouldersDictionaryEntries,
    shouldersSearchAliasRows,
    shouldersMergeTargets,
};
