/**
 * Canonical Triceps exercise catalog.
 *
 * Same architecture as Chest/Back/Shoulders/Biceps.
 * Close-grip pressing lives here (Triceps category) rather than Chest.
 */

/** @typedef {{
 *   name: string,
 *   muscleGroup: "Triceps",
 *   equipment: string,
 *   movementType: string,
 *   primaryMuscles: string[],
 *   secondaryMuscles: string[],
 *   aliases?: string[],
 *   instructions?: string,
 * }} TricepsCatalogEntry */

/** @type {TricepsCatalogEntry[]} */
const TRICEPS_CATALOG = [
    // ── Compound pressing ────────────────────────────────────────────────────
    {
        name: "Close Grip Barbell Bench Press",
        muscleGroup: "Triceps",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: [
            "Close Grip Bench Press",
            "Close-Grip Bench Press",
            "Close-Grip Barbell Bench Press",
            "CGBP",
            "Close Grip Bench",
        ],
        instructions:
            "Lie on a flat bench with a narrower-than-shoulder grip, lower the bar to the lower chest with elbows tucked, then press to lockout.",
    },
    {
        name: "Close Grip Smith Machine Bench Press",
        muscleGroup: "Triceps",
        equipment: "Smith Machine",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: [
            "Smith Machine Close Grip Bench Press",
            "Smith Close Grip Bench Press",
            "Close Grip Smith Bench Press",
        ],
        instructions: "Use a close grip on the Smith bar and press with elbows tucked toward the torso.",
    },
    {
        name: "JM Press",
        muscleGroup: "Triceps",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest"],
        aliases: ["J.M. Press", "JM Bench Press"],
        instructions:
            "From a close-grip bench position, lower the bar toward the upper chest/neck while allowing the elbows to travel forward, then press back to lockout.",
    },
    {
        name: "Smith Machine JM Press",
        muscleGroup: "Triceps",
        equipment: "Smith Machine",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest"],
        aliases: ["Smith JM Press"],
    },
    {
        name: "Floor Press",
        muscleGroup: "Triceps",
        equipment: "Barbell",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Barbell Floor Press", "BB Floor Press"],
        instructions: "Lie on the floor and press the bar from the point where the upper arms touch the ground to lockout.",
    },
    {
        name: "Close Grip Dumbbell Press",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Close-Grip Dumbbell Press", "Close Grip DB Press"],
        instructions: "Press dumbbells with a narrow path and elbows tucked, emphasizing the triceps lockout.",
    },
    {
        name: "Close Grip Machine Press",
        muscleGroup: "Triceps",
        equipment: "Machine",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest"],
        aliases: ["Close-Grip Machine Press"],
    },

    // ── Dips ─────────────────────────────────────────────────────────────────
    {
        name: "Tricep Dip",
        muscleGroup: "Triceps",
        equipment: "Bodyweight",
        movementType: "Dip",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Parallel Bar Dip", "Triceps Dip", "Upright Dip"],
        instructions: "Support on parallel bars with a more upright torso, lower by bending the elbows, then press up to lockout.",
    },
    {
        name: "Weighted Tricep Dip",
        muscleGroup: "Triceps",
        equipment: "Bodyweight",
        movementType: "Dip",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Weighted Triceps Dip"],
        instructions: "Perform tricep dips with added load via a belt, vest, or dumbbell.",
    },
    {
        name: "Assisted Tricep Dip",
        muscleGroup: "Triceps",
        equipment: "Machine",
        movementType: "Dip",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Assisted Triceps Dip"],
    },
    {
        name: "Bench Dip",
        muscleGroup: "Triceps",
        equipment: "Bodyweight",
        movementType: "Dip",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Bench Dips", "Chair Dip"],
        instructions: "Support on a bench behind you, lower by bending the elbows, then press back up.",
    },
    {
        name: "Weighted Bench Dip",
        muscleGroup: "Triceps",
        equipment: "Bodyweight",
        movementType: "Dip",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: [],
    },

    // ── Pushdowns ────────────────────────────────────────────────────────────
    {
        name: "Straight Bar Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: [
            "Tricep Pushdown",
            "Triceps Pushdown",
            "Tricep Pressdown",
            "Triceps Pressdown",
            "Cable Pushdown",
            "Bar Tricep Pushdown",
        ],
        instructions: "Push a straight bar down until the elbows lock out, keeping the upper arms pinned to the sides, then return with control.",
    },
    {
        name: "Rope Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Tricep Rope Pushdown", "Rope Pushdown", "Cable Rope Pushdown"],
        instructions: "Push the rope down and slightly apart at the bottom to finish the triceps contraction.",
    },
    {
        name: "V-Bar Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["V Bar Tricep Pushdown", "V-Bar Pushdown"],
    },
    {
        name: "Reverse Grip Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Reverse-Grip Tricep Pushdown", "Underhand Tricep Pushdown"],
        instructions: "Use an underhand grip on a bar and push down to lockout with elbows fixed.",
    },
    {
        name: "Single Arm Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Tricep Pushdown", "One Arm Tricep Pushdown"],
    },
    {
        name: "Single Arm Rope Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Rope Tricep Pushdown"],
    },
    {
        name: "Single Arm Reverse Grip Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Reverse Grip Tricep Pushdown"],
    },
    {
        name: "Cross Body Cable Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Cross-Body Cable Tricep Extension", "Cross Body Tricep Extension"],
    },

    // ── Overhead cable ───────────────────────────────────────────────────────
    {
        name: "Cable Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Overhead Tricep Extension", "Overhead Cable Extension", "Cable Extension"],
        instructions: "Face away from a high or mid cable and extend the elbows overhead until lockout, then return with control.",
    },
    {
        name: "Rope Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Overhead Rope Extension", "Rope Overhead Extension"],
        instructions: "With a rope behind the head, extend the elbows overhead and slightly separate the rope ends at lockout.",
    },
    {
        name: "Single Arm Cable Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: [
            "Single-Arm Cable Overhead Tricep Extension",
            "Single-Arm Cable Extension",
            "Single Arm Cable Extension",
            "One Arm Cable Extension",
        ],
        instructions: "Extend one arm overhead against a cable, keeping the upper arm still.",
    },
    {
        name: "Single Arm Rope Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Rope Overhead Tricep Extension"],
    },
    {
        name: "Seated Cable Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: [],
    },
    {
        name: "Kneeling Cable Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: [],
    },

    // ── Dumbbell extensions ──────────────────────────────────────────────────
    {
        name: "Dumbbell Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["DB Overhead Tricep Extension", "Two Arm Dumbbell Overhead Extension"],
        instructions: "Hold a dumbbell overhead with both hands, lower it behind the head by bending the elbows, then extend to lockout.",
    },
    {
        name: "Single Arm Dumbbell Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Dumbbell Overhead Tricep Extension", "One Arm Overhead Extension"],
    },
    {
        name: "Seated Dumbbell Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Seated Overhead Dumbbell Extension"],
    },
    {
        name: "Lying Dumbbell Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Lying DB Tricep Extension"],
    },
    {
        name: "Dumbbell Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["DB Skull Crusher"],
        instructions: "Lie on a bench and lower dumbbells toward the forehead or temples by bending the elbows, then extend to lockout.",
    },
    {
        name: "Single Arm Dumbbell Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Dumbbell Skull Crusher"],
    },
    {
        name: "Tate Press",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest"],
        aliases: ["Dumbbell Tate Press", "DB Tate Press"],
        instructions: "Lie on a bench holding dumbbells over the chest, lower the elbows out as the weights move toward the chest, then extend.",
    },

    // ── Skull crushers ───────────────────────────────────────────────────────
    {
        name: "EZ Bar Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "EZ Bar",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Skull Crusher", "Skull Crushers", "Lying Tricep Extension", "EZ Skull Crusher"],
        instructions: "Lie on a bench and lower an EZ bar toward the forehead by bending the elbows, then extend to lockout.",
    },
    {
        name: "Barbell Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "Barbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Straight Bar Skull Crusher"],
    },
    {
        name: "Cable Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Lying Cable Tricep Extension"],
    },
    {
        name: "Single Arm Cable Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Cable Skull Crusher"],
    },
    {
        name: "Incline Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "EZ Bar",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Incline EZ Bar Skull Crusher"],
    },
    {
        name: "Decline Skull Crusher",
        muscleGroup: "Triceps",
        equipment: "EZ Bar",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Decline EZ Bar Skull Crusher"],
    },

    // ── Kickbacks ────────────────────────────────────────────────────────────
    {
        name: "Dumbbell Tricep Kickback",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Tricep Kickback", "Dumbbell Kickback", "DB Kickback"],
        instructions: "Hinge forward with the upper arm parallel to the floor and extend the elbow to lockout behind you.",
    },
    {
        name: "Single Arm Dumbbell Tricep Kickback",
        muscleGroup: "Triceps",
        equipment: "Dumbbell",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Dumbbell Tricep Kickback", "One Arm Kickback"],
    },
    {
        name: "Cable Tricep Kickback",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Cable Kickback"],
        instructions: "With a cable behind you, keep the upper arm still and extend the elbow to lockout.",
    },
    {
        name: "Single Arm Cable Tricep Kickback",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Cable Tricep Kickback"],
    },
    {
        name: "Rope Cable Kickback",
        muscleGroup: "Triceps",
        equipment: "Cable",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Rope Kickback", "Cable Rope Kickback"],
    },

    // ── Machine ──────────────────────────────────────────────────────────────
    {
        name: "Machine Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Machine",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Tricep Extension Machine", "Machine Overhead Tricep Extension"],
        instructions: "Adjust the machine pads and extend the elbows through a full range without shrugging.",
    },
    {
        name: "Single Arm Machine Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Machine",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Machine Tricep Extension"],
    },
    {
        name: "Machine Dip",
        muscleGroup: "Triceps",
        equipment: "Machine",
        movementType: "Dip",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Dip Machine", "Machine Tricep Dip"],
    },
    {
        name: "Assisted Dip Machine",
        muscleGroup: "Triceps",
        equipment: "Machine",
        movementType: "Dip",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "frontDelts"],
        aliases: ["Machine Assisted Dip"],
    },
    {
        name: "Plate Loaded Tricep Press",
        muscleGroup: "Triceps",
        equipment: "Plate Loaded",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest"],
        aliases: ["Hammer Strength Tricep Press", "Plate-Loaded Tricep Press"],
    },
    {
        name: "Single Arm Plate Loaded Tricep Press",
        muscleGroup: "Triceps",
        equipment: "Plate Loaded",
        movementType: "Press",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest"],
        aliases: ["Single-Arm Plate Loaded Tricep Press"],
    },

    // ── Resistance band ──────────────────────────────────────────────────────
    {
        name: "Resistance Band Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Resistance Band",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Band Tricep Pushdown", "Band Pushdown"],
    },
    {
        name: "Single Arm Resistance Band Tricep Pushdown",
        muscleGroup: "Triceps",
        equipment: "Resistance Band",
        movementType: "Pushdown",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Band Tricep Pushdown", "Single Arm Band Pushdown"],
    },
    {
        name: "Resistance Band Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Resistance Band",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Band Overhead Tricep Extension"],
    },
    {
        name: "Single Arm Resistance Band Overhead Tricep Extension",
        muscleGroup: "Triceps",
        equipment: "Resistance Band",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Single-Arm Band Overhead Tricep Extension"],
    },
    {
        name: "Resistance Band Tricep Kickback",
        muscleGroup: "Triceps",
        equipment: "Resistance Band",
        movementType: "Elbow Extension",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        aliases: ["Band Tricep Kickback", "Band Kickback"],
    },
];

const TRICEPS_KEY_ALIASES = {
    // Compounds
    "close grip bench press": "close grip barbell bench press",
    "close grip bench": "close grip barbell bench press",
    "cgbp": "close grip barbell bench press",
    "smith machine close grip bench press": "close grip smith machine bench press",
    "smith close grip bench press": "close grip smith machine bench press",
    "close grip smith bench press": "close grip smith machine bench press",
    "j m press": "jm press",
    "jm bench press": "jm press",
    "smith jm press": "smith machine jm press",
    "barbell floor press": "floor press",
    "bb floor press": "floor press",
    "close grip db press": "close grip dumbbell press",

    // Dips
    "parallel bar dip": "tricep dip",
    "triceps dip": "tricep dip",
    "upright dip": "tricep dip",
    "weighted triceps dip": "weighted tricep dip",
    "assisted triceps dip": "assisted tricep dip",
    "bench dips": "bench dip",
    "chair dip": "bench dip",
    "assisted dip": "assisted dip machine",
    "machine assisted dip": "assisted dip machine",
    "dip machine": "machine dip",
    "machine tricep dip": "machine dip",

    // Pushdowns
    "tricep pushdown": "straight bar tricep pushdown",
    "triceps pushdown": "straight bar tricep pushdown",
    "tricep pressdown": "straight bar tricep pushdown",
    "triceps pressdown": "straight bar tricep pushdown",
    "cable pushdown": "straight bar tricep pushdown",
    "bar tricep pushdown": "straight bar tricep pushdown",
    "tricep rope pushdown": "rope tricep pushdown",
    "rope pushdown": "rope tricep pushdown",
    "cable rope pushdown": "rope tricep pushdown",
    "v bar tricep pushdown": "v bar tricep pushdown",
    "v bar pushdown": "v bar tricep pushdown",
    "reverse grip tricep pushdown": "reverse grip tricep pushdown",
    "underhand tricep pushdown": "reverse grip tricep pushdown",
    "one arm tricep pushdown": "single arm tricep pushdown",
    "cross body tricep extension": "cross body cable tricep extension",

    // Overhead
    "overhead tricep extension": "cable overhead tricep extension",
    "overhead cable extension": "cable overhead tricep extension",
    "cable extension": "cable overhead tricep extension",
    "overhead rope extension": "rope overhead tricep extension",
    "rope overhead extension": "rope overhead tricep extension",
    "single arm cable extension": "single arm cable overhead tricep extension",
    "one arm cable extension": "single arm cable overhead tricep extension",

    // Dumbbell
    "db overhead tricep extension": "dumbbell overhead tricep extension",
    "two arm dumbbell overhead extension": "dumbbell overhead tricep extension",
    "one arm overhead extension": "single arm dumbbell overhead tricep extension",
    "seated overhead dumbbell extension": "seated dumbbell overhead tricep extension",
    "lying db tricep extension": "lying dumbbell tricep extension",
    "db skull crusher": "dumbbell skull crusher",
    "dumbbell tate press": "tate press",
    "db tate press": "tate press",

    // Skull crushers
    "skull crusher": "ez bar skull crusher",
    "skull crushers": "ez bar skull crusher",
    "lying tricep extension": "ez bar skull crusher",
    "ez skull crusher": "ez bar skull crusher",
    "straight bar skull crusher": "barbell skull crusher",
    "lying cable tricep extension": "cable skull crusher",
    "incline ez bar skull crusher": "incline skull crusher",
    "decline ez bar skull crusher": "decline skull crusher",

    // Kickbacks
    "tricep kickback": "dumbbell tricep kickback",
    "dumbbell kickback": "dumbbell tricep kickback",
    "db kickback": "dumbbell tricep kickback",
    "one arm kickback": "single arm dumbbell tricep kickback",
    "cable kickback": "cable tricep kickback",
    "rope kickback": "rope cable kickback",
    "cable rope kickback": "rope cable kickback",

    // Machine / band
    "tricep extension machine": "machine tricep extension",
    "machine overhead tricep extension": "machine tricep extension",
    "hammer strength tricep press": "plate loaded tricep press",
    "band tricep pushdown": "resistance band tricep pushdown",
    "band pushdown": "resistance band tricep pushdown",
    "single arm band pushdown": "single arm resistance band tricep pushdown",
    "band overhead tricep extension": "resistance band overhead tricep extension",
    "band tricep kickback": "resistance band tricep kickback",
    "band kickback": "resistance band tricep kickback",
};

function tricepsDictionaryEntries() {
    return TRICEPS_CATALOG.map((entry) => ({
        name: entry.name,
        muscleGroup: entry.muscleGroup,
        ...(entry.instructions ? { instructions: entry.instructions } : {}),
    }));
}

function tricepsSearchAliasRows() {
    const rows = [];
    for (const entry of TRICEPS_CATALOG) {
        for (const alias of entry.aliases ?? []) {
            rows.push({
                alias,
                name: entry.name,
                muscleGroup: entry.muscleGroup,
            });
        }
    }
    return rows;
}

function tricepsMergeTargets() {
    return TRICEPS_CATALOG.map((entry) => ({
        targetName: entry.name,
        targetMuscleGroup: entry.muscleGroup,
        sourceNames: [...new Set([...(entry.aliases ?? [])])],
    })).filter((row) => row.sourceNames.length > 0);
}

module.exports = {
    TRICEPS_CATALOG,
    TRICEPS_KEY_ALIASES,
    tricepsDictionaryEntries,
    tricepsSearchAliasRows,
    tricepsMergeTargets,
};
