/**
 * Back identity-key aliases — kept in `src/` so client bundles don't require
 * `scripts/catalog`. Keep in sync with `scripts/catalog/back.js` BACK_KEY_ALIASES.
 */
export const BACK_KEY_ALIASES: Record<string, string> = {
    "pull ups": "pull up",
    "pullups": "pull up",
    "chin ups": "chin up",
    "chinups": "chin up",
    "neutral grip pullup": "neutral grip pull up",
    "hammer grip pull up": "neutral grip pull up",
    "close grip pullup": "close grip pull up",
    "wide grip pullup": "wide grip pull up",
    "weighted pullup": "weighted pull up",
    "weighted chinup": "weighted chin up",
    "machine assisted pull up": "assisted pull up",
    "assisted pullup": "assisted pull up",
    "banded pull up": "band assisted pull up",
    "resistance band assisted pull up": "band assisted pull up",
    "gymnastic ring pull up": "ring pull up",
    "sternum pullup": "sternum pull up",
    "gironda pull up": "sternum pull up",
    "lat pull down": "lat pulldown",
    "cable lat pulldown": "lat pulldown",
    "front lat pulldown": "lat pulldown",
    "wide grip lat pulldown": "wide grip lat pulldown",
    "close grip lat pulldown": "close grip lat pulldown",
    "neutral grip lat pulldown": "neutral grip lat pulldown",
    "hammer grip lat pulldown": "neutral grip lat pulldown",
    "reverse grip lat pulldown": "reverse grip lat pulldown",
    "underhand lat pulldown": "reverse grip lat pulldown",
    "one arm lat pulldown": "single arm lat pulldown",
    "lat pulldown machine": "machine lat pulldown",
    "plate loaded lat pulldown": "plate loaded lat pulldown",
    "straight arm pulldown": "straight arm cable pulldown",
    "straight arm lat pulldown": "straight arm cable pulldown",
    "straight arm rope pulldown": "rope straight arm pulldown",
    "lat pullover": "cable lat pullover",
    "cable pullover": "cable lat pullover",
    "db pullover": "dumbbell pullover",
    "dumbbell lat pullover": "dumbbell pullover",
    "nautilus pullover": "machine pullover",
    "band straight arm pulldown": "resistance band straight arm pulldown",
    "bent over row": "barbell row",
    "bent over barbell row": "barbell row",
    "barbell bent over row": "barbell row",
    "bb row": "barbell row",
    "reverse grip barbell row": "underhand barbell row",
    "underhand bent over row": "underhand barbell row",
    "wide grip barbell row": "wide grip barbell row",
    "barbell seal row": "seal row",
    "prone bench row": "seal row",
    "chest supported row": "barbell chest supported row",
    "chest supported barbell row": "barbell chest supported row",
    "single arm dumbbell row": "single arm dumbbell row",
    "one arm dumbbell row": "single arm dumbbell row",
    "dumbbell row": "single arm dumbbell row",
    "db row": "single arm dumbbell row",
    "single arm db row": "single arm dumbbell row",
    "two arm dumbbell row": "dumbbell bent over row",
    "bent over dumbbell row": "dumbbell bent over row",
    "chest supported dumbbell row": "chest supported dumbbell row",
    "incline dumbbell row": "chest supported dumbbell row",
    "incline bench db row": "incline bench dumbbell row",
    "db seal row": "dumbbell seal row",
    "cable row": "seated cable row",
    "seated row": "seated cable row",
    "close grip cable row": "close grip seated cable row",
    "close grip seated cable row": "close grip seated cable row",
    "wide grip cable row": "wide grip seated cable row",
    "wide grip seated cable row": "wide grip seated cable row",
    "reverse grip seated cable row": "underhand seated cable row",
    "underhand cable row": "underhand seated cable row",
    "standing single arm cable row": "single arm standing cable row",
    "seated rope cable row": "rope seated cable row",
    "seated machine row": "machine row",
    "selectorized row": "machine row",
    "plate loaded row": "plate loaded row",
    "hammer strength row": "plate loaded row",
    "hs row": "plate loaded row",
    "plate loaded chest supported row": "plate loaded chest supported row",
    "hammer strength chest supported row": "plate loaded chest supported row",
    "hammer strength single arm row": "single arm plate loaded row",
    "machine high row": "high row machine",
    "machine low row": "low row machine",
    "isolateral row": "iso lateral row",
    "iso lateral row": "iso lateral row",
    "t bar row": "t bar row",
    "tbar row": "t bar row",
    "chest supported t bar row": "chest supported t bar row",
    "supported t bar row": "chest supported t bar row",
    "landmine barbell row": "landmine row",
    "australian pull up": "inverted row",
    "australian pullup": "inverted row",
    "bodyweight row": "inverted row",
    "horizontal pull up": "inverted row",
    "gymnastic ring row": "ring row",
    "feet elevated bodyweight row": "feet elevated inverted row",
    "deadlift": "conventional deadlift",
    "barbell deadlift": "conventional deadlift",
    "conventional barbell deadlift": "conventional deadlift",
    "bb deadlift": "conventional deadlift",
    "sumo barbell deadlift": "sumo deadlift",
    "hex bar deadlift": "trap bar deadlift",
    "trapbar deadlift": "trap bar deadlift",
    "partial deadlift": "rack pull",
    "above knee rack pull": "rack pull",
    "block deadlift": "block pull",
    "elevated deadlift": "block pull",
    "snatch grip deadlift": "snatch grip deadlift",
    "pause deadlift": "paused deadlift",
    "rdl": "romanian deadlift",
    "barbell romanian deadlift": "romanian deadlift",
    "barbell rdl": "romanian deadlift",
    "hyperextension": "back extension",
    "hyper extension": "back extension",
    "back extensions": "back extension",
    "45 degree hyperextension": "45 degree back extension",
    "45 degree back extension": "45 degree back extension",
    "90 degree back extension": "90 degree back extension",
    "horizontal back extension": "90 degree back extension",
    "ghd back extension": "90 degree back extension",
    "weighted hyperextension": "weighted back extension",
    "back extension machine": "machine back extension",
    "reverse hyper": "reverse hyperextension",
    "reverse hyperextensions": "reverse hyperextension",
    "good mornings": "good morning",
    "superman hold": "superman",
    "bird dog": "bird dog",
    "scap pull up": "scapular pull up",
    "scapular pullup": "scapular pull up",
    "scapular pulldown": "cable scapular pulldown",
    "band lat pulldown": "resistance band lat pulldown",
    "band row": "resistance band row",
    "single arm band row": "single arm resistance band row",
};
