/**
 * Biceps identity-key aliases — keep in sync with scripts/catalog/biceps.js
 */
export const BICEPS_KEY_ALIASES: Record<string, string> = {
    "barbell bicep curl": "barbell curl",
    "bb curl": "barbell curl",
    "standing barbell curl": "barbell curl",
    "ez bar curl": "ez bar curl",
    "ez curl": "ez bar curl",
    "easy bar curl": "ez bar curl",
    "wide grip curl": "wide grip barbell curl",
    "close grip curl": "close grip barbell curl",
    "reverse grip barbell curl": "reverse barbell curl",
    "overhand barbell curl": "reverse barbell curl",
    "reverse grip ez bar curl": "reverse ez bar curl",
    "overhand ez bar curl": "reverse ez bar curl",
    "barbell drag curl": "drag curl",
    "preacher curl": "ez bar preacher curl",
    "ez preacher curl": "ez bar preacher curl",
    "spider curl": "ez bar spider curl",
    "ez spider curl": "ez bar spider curl",
    "twenty one": "21",
    "twenty ones": "21",
    "21 curl": "21",
    "21s curl": "21",
    "barbell 21": "21",
    "standing dumbbell curl": "dumbbell curl",
    "db curl": "dumbbell curl",
    "bicep curl": "dumbbell curl",
    "dumbbell bicep curl": "dumbbell curl",
    "alternating curl": "alternating dumbbell curl",
    "alt dumbbell curl": "alternating dumbbell curl",
    "one arm dumbbell curl": "single arm dumbbell curl",
    "one arm curl": "single arm dumbbell curl",
    "incline curl": "incline dumbbell curl",
    "incline db curl": "incline dumbbell curl",
    "alternating incline curl": "alternating incline dumbbell curl",
    "seated curl": "seated dumbbell curl",
    "dumbbell concentration curl": "concentration curl",
    "spider dumbbell curl": "dumbbell spider curl",
    "db spider curl": "dumbbell spider curl",
    "db preacher curl": "dumbbell preacher curl",
    "one arm preacher curl": "single arm dumbbell preacher curl",
    "db drag curl": "dumbbell drag curl",
    "zottman dumbbell curl": "zottman curl",
    "overhand dumbbell curl": "reverse dumbbell curl",
    "reverse grip dumbbell curl": "reverse dumbbell curl",
    "dumbbell hammer curl": "hammer curl",
    "neutral grip curl": "hammer curl",
    "db hammer curl": "hammer curl",
    "alternating dumbbell hammer curl": "alternating hammer curl",
    "one arm hammer curl": "single arm hammer curl",
    "cross body hammer curl": "cross body hammer curl",
    "crossbody hammer curl": "cross body hammer curl",
    "incline dumbbell hammer curl": "incline hammer curl",
    "cable rope hammer curl": "rope hammer curl",
    "rope curl": "rope hammer curl",
    "neutral grip cable curl": "cable hammer curl",
    "cable bicep curl": "cable curl",
    "standing cable curl": "cable curl",
    "one arm cable curl": "single arm cable curl",
    "cable rope curl": "rope cable curl",
    "cable ez bar curl": "ez bar cable curl",
    "cable straight bar curl": "straight bar cable curl",
    "bar cable curl": "straight bar cable curl",
    "bayesian cable curl": "bayesian curl",
    "behind body bayesian curl": "bayesian curl",
    "behind body cable curl": "behind the body cable curl",
    "overhead cable curl": "high cable curl",
    "high pulley curl": "high cable curl",
    "supine cable curl": "lying cable curl",
    "reverse grip cable curl": "reverse cable curl",
    "overhand cable curl": "reverse cable curl",
    "machine curl": "machine bicep curl",
    "bicep curl machine": "machine bicep curl",
    "selectorized bicep curl": "machine bicep curl",
    "preacher curl machine": "machine preacher curl",
    "single arm machine curl": "single arm machine bicep curl",
    "single arm dumbbell spider curl": "single arm spider curl",
    "band curl": "resistance band curl",
    "band bicep curl": "resistance band curl",
    "single arm band curl": "single arm resistance band curl",
    "band hammer curl": "resistance band hammer curl",
    "band preacher curl": "resistance band preacher curl",
};
