/**
 * Chest identity-key aliases — kept in `src/` so client bundles don't require
 * `scripts/catalog`. Keep in sync with `scripts/catalog/chest.js` CHEST_KEY_ALIASES.
 */
export const CHEST_KEY_ALIASES: Record<string, string> = {
    "bench press": "barbell bench press",
    "flat bench press": "barbell bench press",
    "bb bench press": "barbell bench press",
    "flat barbell bench press": "barbell bench press",
    "incline bench press": "incline barbell bench press",
    "incline bb bench press": "incline barbell bench press",
    "decline bench press": "decline barbell bench press",
    "decline bb bench press": "decline barbell bench press",
    "close grip bench press": "close grip barbell bench press",
    "wide grip bench press": "wide grip barbell bench press",
    "paused bench press": "paused barbell bench press",
    "pause bench press": "paused barbell bench press",
    "spoto bench press": "spoto press",
    "floor press": "barbell floor press",
    "bb floor press": "barbell floor press",
    "guillotine bench press": "guillotine press",
    "neck press": "guillotine press",
    "db bench press": "dumbbell bench press",
    "flat dumbbell bench press": "dumbbell bench press",
    "dumbbell flat bench press": "dumbbell bench press",
    "incline dumbbell press": "incline dumbbell bench press",
    "incline db bench press": "incline dumbbell bench press",
    "incline db press": "incline dumbbell bench press",
    "decline dumbbell press": "decline dumbbell bench press",
    "decline db bench press": "decline dumbbell bench press",
    "neutral grip db bench press": "neutral grip dumbbell bench press",
    "hammer grip dumbbell bench press": "neutral grip dumbbell bench press",
    "incline neutral grip dumbbell press": "incline neutral grip dumbbell bench press",
    "one arm dumbbell bench press": "single arm dumbbell bench press",
    "single arm incline dumbbell press": "single arm incline dumbbell bench press",
    "db floor press": "dumbbell floor press",
    "chest fly": "dumbbell chest fly",
    "dumbbell fly": "dumbbell chest fly",
    "flat dumbbell fly": "dumbbell chest fly",
    "flat dumbbell chest fly": "dumbbell chest fly",
    "db chest fly": "dumbbell chest fly",
    "db fly": "dumbbell chest fly",
    "incline dumbbell fly": "incline dumbbell chest fly",
    "incline db fly": "incline dumbbell chest fly",
    "incline chest fly": "incline dumbbell chest fly",
    "decline dumbbell fly": "decline dumbbell chest fly",
    "decline db fly": "decline dumbbell chest fly",
    "squeeze press": "dumbbell squeeze press",
    "hex press": "dumbbell squeeze press",
    "smith bench press": "smith machine bench press",
    "smith machine incline press": "smith machine incline bench press",
    "smith incline bench press": "smith machine incline bench press",
    "smith machine decline press": "smith machine decline bench press",
    "smith close grip bench press": "smith machine close grip bench press",
    "chest press machine": "machine chest press",
    "seated chest press": "machine chest press",
    "incline machine press": "incline machine chest press",
    "incline chest press machine": "incline machine chest press",
    "decline machine press": "decline machine chest press",
    "converging machine chest press": "converging chest press",
    "standing cable chest press": "cable chest press",
    "cable press": "cable chest press",
    "incline cable press": "incline cable chest press",
    "decline cable press": "decline cable chest press",
    "cable fly": "cable chest fly",
    "standing cable fly": "cable chest fly",
    "cable crossover": "cable chest fly",
    "mid cable fly": "cable chest fly",
    "low cable fly": "low to high cable fly",
    "cable low to high fly": "low to high cable fly",
    "high cable fly": "high to low cable fly",
    "cable high to low fly": "high to low cable fly",
    "incline cable chest fly": "incline cable fly",
    "pec deck": "pec deck fly",
    "pec deck machine": "pec deck fly",
    "butterfly machine": "pec deck fly",
    "machine fly": "machine chest fly",
    "chest fly machine": "machine chest fly",
    "dips chest": "chest dip",
    "chest dips": "chest dip",
    "weighted dip": "weighted chest dip",
    "weighted chest dips": "weighted chest dip",
    "assisted dip": "assisted chest dip",
    "machine assisted chest dip": "assisted chest dip",
    "wide push up": "wide grip push up",
    "wide pushup": "wide grip push up",
    "close push up": "close grip push up",
    "triangle push up": "diamond push up",
    "banded push up": "resistance band push up",
    "band push up": "resistance band push up",
    "plyo push up": "plyometric push up",
    "explosive push up": "plyometric push up",
    "clapping push up": "clap push up",
    "single arm push up": "one arm push up",
    "kneeling push up": "knee push up",
    "knee pushup": "knee push up",
    "wall pushup": "wall push up",
    "plate squeeze press": "svend press",
    "landmine press": "landmine chest press",
    "standing landmine chest press": "landmine chest press",
    "single arm landmine press": "single arm landmine chest press",
    "band chest press": "resistance band chest press",
    "single arm band chest press": "single arm resistance band chest press",
    "band chest fly": "resistance band chest fly",
    "band fly": "resistance band chest fly",
    "single arm band chest fly": "single arm resistance band chest fly",
};
