/**
 * Forearms identity-key aliases — keep in sync with scripts/catalog/forearms.js
 */
export const FOREARMS_KEY_ALIASES: Record<string, string> = {
    "wrist curl": "barbell wrist curl",
    "bb wrist curl": "barbell wrist curl",
    "seated barbell wrist curl": "barbell wrist curl",
    "forearm curl": "barbell wrist curl",
    "db wrist curl": "dumbbell wrist curl",
    "one arm wrist curl": "single arm dumbbell wrist curl",
    "behind back wrist curl": "behind the back barbell wrist curl",
    "wrist curl machine": "machine wrist curl",
    "reverse wrist curl": "barbell reverse wrist curl",
    "bb reverse wrist curl": "barbell reverse wrist curl",
    "overhand wrist curl": "barbell reverse wrist curl",
    "db reverse wrist curl": "dumbbell reverse wrist curl",
    "wrist roll": "wrist roller",
    "forearm roller": "wrist roller",
    "grip trainer": "hand gripper",
    "hand grip": "hand gripper",
    "gripper": "hand gripper",
    "captains of crush": "hand gripper",
    "adjustable gripper": "adjustable hand gripper",
    "closed gripper hold": "gripper hold",
    "towel crush": "towel squeeze",
    "plate pinch": "plate pinch hold",
    "pinch hold": "plate pinch hold",
    "plate pinch grip": "plate pinch hold",
    "pinch carry": "plate pinch carry",
    "bar hang": "dead hang",
    "passive hang": "dead hang",
    "weighted hang": "weighted dead hang",
    "one arm hang": "single arm dead hang",
    "towel hang": "towel dead hang",
    "thick bar dead hang": "fat grip dead hang",
    "fat bar hang": "fat grip dead hang",
    "farmers walk": "farmer carry",
    "farmer walk": "farmer carry",
    "farmers carry": "farmer carry",
    "farmer carry": "farmer carry",
    "suitcase walk": "suitcase carry",
    "single arm farmer carry": "suitcase carry",
    "hex bar carry": "trap bar carry",
    "trap bar farmer walk": "trap bar carry",
    "db farmer carry": "dumbbell farmer carry",
    "dumbbell farmers walk": "dumbbell farmer carry",
    "kb farmer carry": "kettlebell farmer carry",
    "kettlebell farmers walk": "kettlebell farmer carry",
    "bottoms up carry": "bottoms up kettlebell carry",
    "wrist pronation": "dumbbell wrist pronation",
    "db pronation": "dumbbell wrist pronation",
    "wrist supination": "dumbbell wrist supination",
    "db supination": "dumbbell wrist supination",
    "radial deviation": "dumbbell radial deviation",
    "ulnar deviation": "dumbbell ulnar deviation",
    "wrist lever": "dumbbell wrist lever",
    "db lever": "dumbbell wrist lever",
    "sledge lever": "sledgehammer wrist lever",
    "hammer lever": "sledgehammer wrist lever",
    "thick bar hold": "fat grip hold",
    "fat bar hold": "fat grip hold",
    "barbell static hold": "barbell hold",
    "double overhand hold": "double overhand barbell hold",
    "pronated barbell hold": "double overhand barbell hold",
    "rack hold": "rack barbell hold",
    "pin hold": "rack barbell hold",
    "db hold": "dumbbell hold",
    "dumbbell static hold": "dumbbell hold",
    "hex bar hold": "trap bar hold",
};
