/**
 * Shoulders identity-key aliases — keep in sync with scripts/catalog/shoulders.js
 */
export const SHOULDERS_KEY_ALIASES: Record<string, string> = {
    "overhead press": "barbell overhead press",
    "military press": "barbell overhead press",
    "ohp": "barbell overhead press",
    "barbell shoulder press": "barbell overhead press",
    "standing barbell overhead press": "barbell overhead press",
    "strict press": "barbell overhead press",
    "standing military press": "barbell overhead press",
    "seated military press": "seated barbell overhead press",
    "behind the neck press": "behind the neck press",
    "behind neck press": "behind the neck press",
    "btn press": "behind the neck press",
    "z press": "barbell z press",
    "seated floor barbell press": "barbell z press",
    "pin press overhead": "barbell shoulder press from pin",
    "overhead press from pin": "barbell shoulder press from pin",
    "dumbbell shoulder press": "seated dumbbell shoulder press",
    "seated dumbbell press": "seated dumbbell shoulder press",
    "seated db shoulder press": "seated dumbbell shoulder press",
    "dumbbell press": "seated dumbbell shoulder press",
    "db shoulder press": "seated dumbbell shoulder press",
    "standing dumbbell press": "standing dumbbell shoulder press",
    "neutral grip dumbbell shoulder press": "neutral grip dumbbell shoulder press",
    "hammer grip dumbbell shoulder press": "neutral grip dumbbell shoulder press",
    "one arm dumbbell shoulder press": "single arm dumbbell shoulder press",
    "arnold dumbbell press": "arnold press",
    "seated arnold press": "arnold press",
    "db z press": "dumbbell z press",
    "smith shoulder press": "smith machine shoulder press",
    "smith machine overhead press": "smith machine shoulder press",
    "shoulder press machine": "machine shoulder press",
    "seated machine shoulder press": "machine shoulder press",
    "hammer strength shoulder press": "plate loaded shoulder press",
    "hs shoulder press": "plate loaded shoulder press",
    "plate loaded shoulder press": "plate loaded shoulder press",
    "standing landmine press": "landmine shoulder press",
    "landmine overhead press": "landmine shoulder press",
    "single arm landmine press": "single arm landmine shoulder press",
    "half kneeling landmine press": "half kneeling landmine press",
    "tall kneeling landmine press": "kneeling landmine press",
    "lateral raise": "dumbbell lateral raise",
    "side raise": "dumbbell lateral raise",
    "side lateral raise": "dumbbell lateral raise",
    "db lateral raise": "dumbbell lateral raise",
    "seated lateral raise": "seated dumbbell lateral raise",
    "lean away dumbbell lateral raise": "leaning dumbbell lateral raise",
    "incline lateral raise": "incline dumbbell lateral raise",
    "one arm lateral raise": "single arm dumbbell lateral raise",
    "lu lateral raise": "lu raise",
    "cable side raise": "cable lateral raise",
    "one arm cable lateral raise": "single arm cable lateral raise",
    "one arm cable lateral": "single arm cable lateral raise",
    "behind back cable lateral raise": "behind the back cable lateral raise",
    "lean away cable lateral raise": "leaning cable lateral raise",
    "ankle cuff cable lateral raise": "cuffed cable lateral raise",
    "cable cuff lateral raise": "cuffed cable lateral raise",
    "lateral raise machine": "machine lateral raise",
    "front raise": "dumbbell front raise",
    "db front raise": "dumbbell front raise",
    "alternating front raise": "alternating dumbbell front raise",
    "one arm front raise": "single arm dumbbell front raise",
    "rope front raise": "rope cable front raise",
    "weight plate front raise": "plate front raise",
    "band front raise": "resistance band front raise",
    "rear delt fly": "dumbbell rear delt fly",
    "bent over rear delt fly": "dumbbell rear delt fly",
    "db rear delt fly": "dumbbell rear delt fly",
    "seated rear delt fly": "seated dumbbell rear delt fly",
    "chest supported rear delt fly": "chest supported dumbbell rear delt fly",
    "incline rear delt fly": "incline bench rear delt fly",
    "rear delt row": "dumbbell rear delt row",
    "rear delt cable fly": "cable rear delt fly",
    "cable reverse fly": "cable rear delt fly",
    "standing cable rear delt fly": "cable rear delt fly",
    "cross body cable rear delt fly": "cross body rear delt fly",
    "rear delt machine fly": "reverse pec deck",
    "rear delt machine": "reverse pec deck",
    "machine rear delt fly": "reverse pec deck",
    "reverse pec deck fly": "reverse pec deck",
    "reverse fly machine": "reverse pec deck",
    "single arm machine rear delt fly": "single arm reverse pec deck",
    "cable face pull": "face pull",
    "rope face pull": "face pull",
    "single arm cable face pull": "single arm face pull",
    "band face pull": "resistance band face pull",
    "upright row": "barbell upright row",
    "bb upright row": "barbell upright row",
    "db upright row": "dumbbell upright row",
    "smith upright row": "smith machine upright row",
    "y raise": "dumbbell y raise",
    "db y raise": "dumbbell y raise",
    "incline dumbbell y raise": "incline y raise",
    "prone dumbbell y raise": "prone y raise",
    "dumbbell w raise": "w raise",
    "dumbbell cuban press": "cuban press",
    "cuban rotation": "cable cuban rotation",
    "cable cuban press": "cable cuban rotation",
    "pike pushup": "pike push up",
    "pike press": "pike push up",
    "feet elevated pike push up": "feet elevated pike push up",
    "hspu": "handstand push up",
    "handstand pushup": "handstand push up",
    "wall hspu": "wall handstand push up",
    "wall supported handstand push up": "wall handstand push up",
    "deficit hspu": "deficit handstand push up",
    "wall handstand hold": "handstand hold",
    "handstand": "handstand hold",
    "wall walks": "wall walk",
    "band shoulder press": "resistance band shoulder press",
    "single arm band shoulder press": "single arm resistance band shoulder press",
    "band lateral raise": "resistance band lateral raise",
    "single arm band lateral raise": "single arm resistance band lateral raise",
    "band rear delt fly": "resistance band rear delt fly",
};
