/**
 * Triceps identity-key aliases — keep in sync with scripts/catalog/triceps.js
 */
export const TRICEPS_KEY_ALIASES: Record<string, string> = {
    "close grip bench press": "close grip barbell bench press",
    "close grip bench": "close grip barbell bench press",
    "cgbp": "close grip barbell bench press",
    "smith machine close grip bench press": "close grip smith machine bench press",
    "smith close grip bench press": "close grip smith machine bench press",
    "close grip smith bench press": "close grip smith machine bench press",
    "j m press": "jm press",
    "jm bench press": "jm press",
    "smith jm press": "smith machine jm press",
    "barbell floor press": "floor press",
    "bb floor press": "floor press",
    "close grip db press": "close grip dumbbell press",
    "parallel bar dip": "tricep dip",
    "triceps dip": "tricep dip",
    "upright dip": "tricep dip",
    "weighted triceps dip": "weighted tricep dip",
    "assisted triceps dip": "assisted tricep dip",
    "bench dips": "bench dip",
    "chair dip": "bench dip",
    "assisted dip": "assisted dip machine",
    "machine assisted dip": "assisted dip machine",
    "dip machine": "machine dip",
    "machine tricep dip": "machine dip",
    "tricep pushdown": "straight bar tricep pushdown",
    "triceps pushdown": "straight bar tricep pushdown",
    "tricep pressdown": "straight bar tricep pushdown",
    "triceps pressdown": "straight bar tricep pushdown",
    "cable pushdown": "straight bar tricep pushdown",
    "bar tricep pushdown": "straight bar tricep pushdown",
    "tricep rope pushdown": "rope tricep pushdown",
    "rope pushdown": "rope tricep pushdown",
    "cable rope pushdown": "rope tricep pushdown",
    "v bar tricep pushdown": "v bar tricep pushdown",
    "v bar pushdown": "v bar tricep pushdown",
    "reverse grip tricep pushdown": "reverse grip tricep pushdown",
    "underhand tricep pushdown": "reverse grip tricep pushdown",
    "one arm tricep pushdown": "single arm tricep pushdown",
    "cross body tricep extension": "cross body cable tricep extension",
    "overhead tricep extension": "cable overhead tricep extension",
    "overhead cable extension": "cable overhead tricep extension",
    "cable extension": "cable overhead tricep extension",
    "overhead rope extension": "rope overhead tricep extension",
    "rope overhead extension": "rope overhead tricep extension",
    "single arm cable extension": "single arm cable overhead tricep extension",
    "one arm cable extension": "single arm cable overhead tricep extension",
    "db overhead tricep extension": "dumbbell overhead tricep extension",
    "two arm dumbbell overhead extension": "dumbbell overhead tricep extension",
    "one arm overhead extension": "single arm dumbbell overhead tricep extension",
    "seated overhead dumbbell extension": "seated dumbbell overhead tricep extension",
    "lying db tricep extension": "lying dumbbell tricep extension",
    "db skull crusher": "dumbbell skull crusher",
    "dumbbell tate press": "tate press",
    "db tate press": "tate press",
    "skull crusher": "ez bar skull crusher",
    "skull crushers": "ez bar skull crusher",
    "lying tricep extension": "ez bar skull crusher",
    "ez skull crusher": "ez bar skull crusher",
    "straight bar skull crusher": "barbell skull crusher",
    "lying cable tricep extension": "cable skull crusher",
    "incline ez bar skull crusher": "incline skull crusher",
    "decline ez bar skull crusher": "decline skull crusher",
    "tricep kickback": "dumbbell tricep kickback",
    "dumbbell kickback": "dumbbell tricep kickback",
    "db kickback": "dumbbell tricep kickback",
    "one arm kickback": "single arm dumbbell tricep kickback",
    "cable kickback": "cable tricep kickback",
    "rope kickback": "rope cable kickback",
    "cable rope kickback": "rope cable kickback",
    "tricep extension machine": "machine tricep extension",
    "machine overhead tricep extension": "machine tricep extension",
    "hammer strength tricep press": "plate loaded tricep press",
    "band tricep pushdown": "resistance band tricep pushdown",
    "band pushdown": "resistance band tricep pushdown",
    "single arm band pushdown": "single arm resistance band tricep pushdown",
    "band overhead tricep extension": "resistance band overhead tricep extension",
    "band tricep kickback": "resistance band tricep kickback",
    "band kickback": "resistance band tricep kickback",
};
